// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sin_or_cos_double_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sin_or_cos_double_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sin_or_cos_double_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state1 = "1";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state2 = "10";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state3 = "100";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state4 = "1000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state5 = "10000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state6 = "100000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state9 = "100000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state10 = "1000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state11 = "10000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state12 = "100000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<25> sin_or_cos_double_s::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_1 = "1";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_2 = "10";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_6 = "110";
const sc_lv<1> sin_or_cos_double_s::ap_const_lv1_0 = "0";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_7 = "111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_8 = "1000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_9 = "1001";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_A = "1010";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_B = "1011";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_C = "1100";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_D = "1101";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_E = "1110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_F = "1111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_10 = "10000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_11 = "10001";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_12 = "10010";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_16 = "10110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_17 = "10111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_3F = "111111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_34 = "110100";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_3E = "111110";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_3FE = "1111111110";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_44D = "10001001101";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_4A = "1001010";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_56 = "1010110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_FF = "11111111";
const sc_lv<1> sin_or_cos_double_s::ap_const_lv1_1 = "1";
const sc_lv<52> sin_or_cos_double_s::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_2B = "101011";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_A6 = "10100110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_A7 = "10100111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_A9 = "10101001";
const sc_lv<3> sin_or_cos_double_s::ap_const_lv3_0 = "000";
const sc_lv<124> sin_or_cos_double_s::ap_const_lv124_0 = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_7B = "1111011";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_3D = "111101";
const sc_lv<2> sin_or_cos_double_s::ap_const_lv2_3 = "11";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_403 = "10000000011";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_0 = "00000000000";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_7FF = "11111111111";
const sc_lv<12> sin_or_cos_double_s::ap_const_lv12_0 = "000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_38 = "111000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_37 = "110111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_31 = "110001";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_61 = "1100001";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_6B = "1101011";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_2D = "101101";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_5C = "1011100";
const sc_lv<4> sin_or_cos_double_s::ap_const_lv4_0 = "0000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_1F = "11111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_3B = "111011";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_26 = "100110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_4A = "1001010";
const sc_lv<63> sin_or_cos_double_s::ap_const_lv63_7FFFFFFFFFFFFFFF = "111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_7D = "1111101";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_3FF = "1111111111";
const sc_lv<52> sin_or_cos_double_s::ap_const_lv52_FFFFFFFFFFFFF = "1111111111111111111111111111111111111111111111111111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_18 = "11000";
const bool sin_or_cos_double_s::ap_const_boolean_1 = true;

sin_or_cos_double_s::sin_or_cos_double_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    ref_4oPi_table_256_V_U = new sin_or_cos_doublecud("ref_4oPi_table_256_V_U");
    ref_4oPi_table_256_V_U->clk(ap_clk);
    ref_4oPi_table_256_V_U->reset(ap_rst);
    ref_4oPi_table_256_V_U->address0(ref_4oPi_table_256_V_address0);
    ref_4oPi_table_256_V_U->ce0(ref_4oPi_table_256_V_ce0);
    ref_4oPi_table_256_V_U->q0(ref_4oPi_table_256_V_q0);
    fourth_order_double_4_U = new sin_or_cos_doubledEe("fourth_order_double_4_U");
    fourth_order_double_4_U->clk(ap_clk);
    fourth_order_double_4_U->reset(ap_rst);
    fourth_order_double_4_U->address0(fourth_order_double_4_address0);
    fourth_order_double_4_U->ce0(fourth_order_double_4_ce0);
    fourth_order_double_4_U->q0(fourth_order_double_4_q0);
    fourth_order_double_5_U = new sin_or_cos_doubleeOg("fourth_order_double_5_U");
    fourth_order_double_5_U->clk(ap_clk);
    fourth_order_double_5_U->reset(ap_rst);
    fourth_order_double_5_U->address0(fourth_order_double_5_address0);
    fourth_order_double_5_U->ce0(fourth_order_double_5_ce0);
    fourth_order_double_5_U->q0(fourth_order_double_5_q0);
    fourth_order_double_6_U = new sin_or_cos_doublefYi("fourth_order_double_6_U");
    fourth_order_double_6_U->clk(ap_clk);
    fourth_order_double_6_U->reset(ap_rst);
    fourth_order_double_6_U->address0(fourth_order_double_6_address0);
    fourth_order_double_6_U->ce0(fourth_order_double_6_ce0);
    fourth_order_double_6_U->q0(fourth_order_double_6_q0);
    fourth_order_double_7_U = new sin_or_cos_doubleg8j("fourth_order_double_7_U");
    fourth_order_double_7_U->clk(ap_clk);
    fourth_order_double_7_U->reset(ap_rst);
    fourth_order_double_7_U->address0(fourth_order_double_7_address0);
    fourth_order_double_7_U->ce0(fourth_order_double_7_ce0);
    fourth_order_double_7_U->q0(fourth_order_double_7_q0);
    fourth_order_double_s_U = new sin_or_cos_doublehbi("fourth_order_double_s_U");
    fourth_order_double_s_U->clk(ap_clk);
    fourth_order_double_s_U->reset(ap_rst);
    fourth_order_double_s_U->address0(fourth_order_double_s_address0);
    fourth_order_double_s_U->ce0(fourth_order_double_s_ce0);
    fourth_order_double_s_U->q0(fourth_order_double_s_q0);
    grp_scaled_fixed2ieee_fu_268 = new scaled_fixed2ieee("grp_scaled_fixed2ieee_fu_268");
    grp_scaled_fixed2ieee_fu_268->ap_clk(ap_clk);
    grp_scaled_fixed2ieee_fu_268->ap_rst(ap_rst);
    grp_scaled_fixed2ieee_fu_268->ap_start(grp_scaled_fixed2ieee_fu_268_ap_start);
    grp_scaled_fixed2ieee_fu_268->ap_done(grp_scaled_fixed2ieee_fu_268_ap_done);
    grp_scaled_fixed2ieee_fu_268->ap_idle(grp_scaled_fixed2ieee_fu_268_ap_idle);
    grp_scaled_fixed2ieee_fu_268->ap_ready(grp_scaled_fixed2ieee_fu_268_ap_ready);
    grp_scaled_fixed2ieee_fu_268->in_V(result_V_reg_1415);
    grp_scaled_fixed2ieee_fu_268->prescale(r_V_reg_1420);
    grp_scaled_fixed2ieee_fu_268->ap_return(grp_scaled_fixed2ieee_fu_268_ap_return);
    convert_mul_170nsibs_U6 = new convert_mul_170nsibs<1,5,170,53,223>("convert_mul_170nsibs_U6");
    convert_mul_170nsibs_U6->clk(ap_clk);
    convert_mul_170nsibs_U6->reset(ap_rst);
    convert_mul_170nsibs_U6->din0(grp_fu_372_p0);
    convert_mul_170nsibs_U6->din1(grp_fu_372_p1);
    convert_mul_170nsibs_U6->ce(ap_var_for_const0);
    convert_mul_170nsibs_U6->dout(grp_fu_372_p2);
    convert_mux_83_1_jbC_U7 = new convert_mux_83_1_jbC<1,1,1,1,1,1,1,1,1,1,3,1>("convert_mux_83_1_jbC_U7");
    convert_mux_83_1_jbC_U7->din0(ap_var_for_const1);
    convert_mux_83_1_jbC_U7->din1(ap_var_for_const2);
    convert_mux_83_1_jbC_U7->din2(ap_var_for_const2);
    convert_mux_83_1_jbC_U7->din3(ap_var_for_const1);
    convert_mux_83_1_jbC_U7->din4(ap_var_for_const1);
    convert_mux_83_1_jbC_U7->din5(ap_var_for_const2);
    convert_mux_83_1_jbC_U7->din6(ap_var_for_const2);
    convert_mux_83_1_jbC_U7->din7(ap_var_for_const1);
    convert_mux_83_1_jbC_U7->din8(p_Val2_29_reg_1164);
    convert_mux_83_1_jbC_U7->dout(tmp_fu_594_p10);
    convert_mul_49ns_kbM_U8 = new convert_mul_49ns_kbM<1,2,49,49,98>("convert_mul_49ns_kbM_U8");
    convert_mul_49ns_kbM_U8->clk(ap_clk);
    convert_mul_49ns_kbM_U8->reset(ap_rst);
    convert_mul_49ns_kbM_U8->din0(grp_fu_618_p0);
    convert_mul_49ns_kbM_U8->din1(grp_fu_618_p1);
    convert_mul_49ns_kbM_U8->ce(ap_var_for_const0);
    convert_mul_49ns_kbM_U8->dout(grp_fu_618_p2);
    convert_mul_49ns_kbM_U9 = new convert_mul_49ns_kbM<1,2,49,49,98>("convert_mul_49ns_kbM_U9");
    convert_mul_49ns_kbM_U9->clk(ap_clk);
    convert_mul_49ns_kbM_U9->reset(ap_rst);
    convert_mul_49ns_kbM_U9->din0(grp_fu_662_p0);
    convert_mul_49ns_kbM_U9->din1(grp_fu_662_p1);
    convert_mul_49ns_kbM_U9->ce(ap_var_for_const0);
    convert_mul_49ns_kbM_U9->dout(grp_fu_662_p2);
    convert_mul_49ns_kbM_U10 = new convert_mul_49ns_kbM<1,2,49,49,98>("convert_mul_49ns_kbM_U10");
    convert_mul_49ns_kbM_U10->clk(ap_clk);
    convert_mul_49ns_kbM_U10->reset(ap_rst);
    convert_mul_49ns_kbM_U10->din0(grp_fu_667_p0);
    convert_mul_49ns_kbM_U10->din1(grp_fu_667_p1);
    convert_mul_49ns_kbM_U10->ce(ap_var_for_const0);
    convert_mul_49ns_kbM_U10->dout(grp_fu_667_p2);
    convert_mul_56ns_lbW_U11 = new convert_mul_56ns_lbW<1,2,56,52,108>("convert_mul_56ns_lbW_U11");
    convert_mul_56ns_lbW_U11->clk(ap_clk);
    convert_mul_56ns_lbW_U11->reset(ap_rst);
    convert_mul_56ns_lbW_U11->din0(grp_fu_679_p0);
    convert_mul_56ns_lbW_U11->din1(fourth_order_double_10_reg_1281);
    convert_mul_56ns_lbW_U11->ce(ap_var_for_const0);
    convert_mul_56ns_lbW_U11->dout(grp_fu_679_p2);
    convert_mul_49ns_mb6_U12 = new convert_mul_49ns_mb6<1,2,49,44,93>("convert_mul_49ns_mb6_U12");
    convert_mul_49ns_mb6_U12->clk(ap_clk);
    convert_mul_49ns_mb6_U12->reset(ap_rst);
    convert_mul_49ns_mb6_U12->din0(grp_fu_691_p0);
    convert_mul_49ns_mb6_U12->din1(fourth_order_double_12_reg_1286);
    convert_mul_49ns_mb6_U12->ce(ap_var_for_const0);
    convert_mul_49ns_mb6_U12->dout(grp_fu_691_p2);
    convert_mul_42ns_ncg_U13 = new convert_mul_42ns_ncg<1,2,42,33,75>("convert_mul_42ns_ncg_U13");
    convert_mul_42ns_ncg_U13->clk(ap_clk);
    convert_mul_42ns_ncg_U13->reset(ap_rst);
    convert_mul_42ns_ncg_U13->din0(grp_fu_750_p0);
    convert_mul_42ns_ncg_U13->din1(grp_fu_750_p1);
    convert_mul_42ns_ncg_U13->ce(ap_var_for_const0);
    convert_mul_42ns_ncg_U13->dout(grp_fu_750_p2);
    convert_mul_64s_6ocq_U14 = new convert_mul_64s_6ocq<1,5,64,63,126>("convert_mul_64s_6ocq_U14");
    convert_mul_64s_6ocq_U14->clk(ap_clk);
    convert_mul_64s_6ocq_U14->reset(ap_rst);
    convert_mul_64s_6ocq_U14->din0(r_V_3_reg_1400);
    convert_mul_64s_6ocq_U14->din1(grp_fu_851_p1);
    convert_mul_64s_6ocq_U14->ce(ap_var_for_const0);
    convert_mul_64s_6ocq_U14->dout(grp_fu_851_p2);
    convert_mux_164_1pcA_U15 = new convert_mux_164_1pcA<1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,1>("convert_mux_164_1pcA_U15");
    convert_mux_164_1pcA_U15->din0(ap_var_for_const1);
    convert_mux_164_1pcA_U15->din1(ap_var_for_const1);
    convert_mux_164_1pcA_U15->din2(ap_var_for_const1);
    convert_mux_164_1pcA_U15->din3(ap_var_for_const2);
    convert_mux_164_1pcA_U15->din4(ap_var_for_const2);
    convert_mux_164_1pcA_U15->din5(ap_var_for_const2);
    convert_mux_164_1pcA_U15->din6(ap_var_for_const2);
    convert_mux_164_1pcA_U15->din7(ap_var_for_const1);
    convert_mux_164_1pcA_U15->din8(ap_var_for_const1);
    convert_mux_164_1pcA_U15->din9(ap_var_for_const2);
    convert_mux_164_1pcA_U15->din10(ap_var_for_const2);
    convert_mux_164_1pcA_U15->din11(ap_var_for_const2);
    convert_mux_164_1pcA_U15->din12(ap_var_for_const2);
    convert_mux_164_1pcA_U15->din13(ap_var_for_const1);
    convert_mux_164_1pcA_U15->din14(ap_var_for_const1);
    convert_mux_164_1pcA_U15->din15(ap_var_for_const1);
    convert_mux_164_1pcA_U15->din16(p_Result_26_fu_911_p3);
    convert_mux_164_1pcA_U15->dout(tmp_3_fu_917_p18);
    convert_mux_164_1pcA_U16 = new convert_mux_164_1pcA<1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,1>("convert_mux_164_1pcA_U16");
    convert_mux_164_1pcA_U16->din0(ap_var_for_const1);
    convert_mux_164_1pcA_U16->din1(ap_var_for_const1);
    convert_mux_164_1pcA_U16->din2(ap_var_for_const2);
    convert_mux_164_1pcA_U16->din3(ap_var_for_const1);
    convert_mux_164_1pcA_U16->din4(ap_var_for_const2);
    convert_mux_164_1pcA_U16->din5(ap_var_for_const2);
    convert_mux_164_1pcA_U16->din6(ap_var_for_const1);
    convert_mux_164_1pcA_U16->din7(ap_var_for_const2);
    convert_mux_164_1pcA_U16->din8(ap_var_for_const2);
    convert_mux_164_1pcA_U16->din9(ap_var_for_const1);
    convert_mux_164_1pcA_U16->din10(ap_var_for_const2);
    convert_mux_164_1pcA_U16->din11(ap_var_for_const2);
    convert_mux_164_1pcA_U16->din12(ap_var_for_const1);
    convert_mux_164_1pcA_U16->din13(ap_var_for_const2);
    convert_mux_164_1pcA_U16->din14(ap_var_for_const1);
    convert_mux_164_1pcA_U16->din15(ap_var_for_const1);
    convert_mux_164_1pcA_U16->din16(p_Result_26_fu_911_p3);
    convert_mux_164_1pcA_U16->dout(tmp_4_fu_955_p18);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Ex_V_fu_505_p2);
    sensitive << ( storemerge_i_fu_477_p3 );
    sensitive << ( tmp_22_i_fu_502_p1 );

    SC_METHOD(thread_Mx_V_read_assign_fu_838_p3);
    sensitive << ( Mx_V_reg_1186 );
    sensitive << ( cos_basis_reg_1393 );

    SC_METHOD(thread_Mx_zeros_V_fu_468_p1);
    sensitive << ( tmp_i3_i_fu_460_p3 );

    SC_METHOD(thread_OP1_V_fu_615_p1);
    sensitive << ( tmp_i1_reg_1229 );

    SC_METHOD(thread_OP2_V_fu_659_p1);
    sensitive << ( tmp_36_i_reg_1275 );

    SC_METHOD(thread_addr_V_fu_312_p3);
    sensitive << ( closepath_fu_300_p2 );
    sensitive << ( expv_op_fu_306_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( p_Result_27_fu_1085_p4 );

    SC_METHOD(thread_closepath_fu_300_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( loc_V_fu_286_p4 );

    SC_METHOD(thread_cos_basis_fu_815_p0);
    sensitive << ( do_cos );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_cos_basis_fu_815_p3);
    sensitive << ( tmp_reg_1240 );
    sensitive << ( cos_basis_fu_815_p0 );
    sensitive << ( tmp_s_fu_810_p2 );

    SC_METHOD(thread_expv_op_fu_306_p2);
    sensitive << ( loc_V_fu_286_p4 );

    SC_METHOD(thread_fourth_order_double_4_address0);
    sensitive << ( tmp_41_i_reg_1258 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_fourth_order_double_4_ce0);
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_fourth_order_double_5_address0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_41_i_fu_643_p1 );

    SC_METHOD(thread_fourth_order_double_5_ce0);
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_fourth_order_double_6_address0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_41_i_fu_643_p1 );

    SC_METHOD(thread_fourth_order_double_6_ce0);
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_fourth_order_double_7_address0);
    sensitive << ( tmp_41_i_reg_1258 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_fourth_order_double_7_ce0);
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_fourth_order_double_s_address0);
    sensitive << ( tmp_41_i_reg_1258 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_fourth_order_double_s_ce0);
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_grp_fu_372_p0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_fu_372_p00 );

    SC_METHOD(thread_grp_fu_372_p00);
    sensitive << ( ret_V_reg_1132 );

    SC_METHOD(thread_grp_fu_372_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_fu_372_p10 );

    SC_METHOD(thread_grp_fu_372_p10);
    sensitive << ( p_Result_20_fu_358_p3 );

    SC_METHOD(thread_grp_fu_618_p0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( OP1_V_fu_615_p1 );

    SC_METHOD(thread_grp_fu_618_p1);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( OP1_V_fu_615_p1 );

    SC_METHOD(thread_grp_fu_662_p0);
    sensitive << ( OP2_V_fu_659_p1 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_grp_fu_662_p1);
    sensitive << ( OP1_V_reg_1246 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_grp_fu_667_p0);
    sensitive << ( OP2_V_fu_659_p1 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_grp_fu_667_p1);
    sensitive << ( OP2_V_fu_659_p1 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_grp_fu_679_p0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( grp_fu_679_p00 );

    SC_METHOD(thread_grp_fu_679_p00);
    sensitive << ( p_Val2_15_reg_1224 );

    SC_METHOD(thread_grp_fu_691_p0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( grp_fu_691_p00 );

    SC_METHOD(thread_grp_fu_691_p00);
    sensitive << ( tmp_36_i_reg_1275 );

    SC_METHOD(thread_grp_fu_750_p0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( grp_fu_750_p00 );

    SC_METHOD(thread_grp_fu_750_p00);
    sensitive << ( tmp_38_i_reg_1333 );

    SC_METHOD(thread_grp_fu_750_p1);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( grp_fu_750_p10 );

    SC_METHOD(thread_grp_fu_750_p10);
    sensitive << ( fourth_order_double_14_reg_1358 );

    SC_METHOD(thread_grp_fu_851_p1);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( grp_fu_851_p10 );

    SC_METHOD(thread_grp_fu_851_p10);
    sensitive << ( Mx_V_read_assign_fu_838_p3 );

    SC_METHOD(thread_grp_scaled_fixed2ieee_fu_268_ap_start);
    sensitive << ( grp_scaled_fixed2ieee_fu_268_ap_start_reg );

    SC_METHOD(thread_loc_V_1_fu_296_p1);
    sensitive << ( p_Val2_s_fu_274_p1 );

    SC_METHOD(thread_loc_V_2_fu_897_p4);
    sensitive << ( p_Val2_25_fu_885_p1 );

    SC_METHOD(thread_loc_V_3_fu_907_p1);
    sensitive << ( p_Val2_25_fu_885_p1 );

    SC_METHOD(thread_loc_V_fu_286_p4);
    sensitive << ( p_Val2_s_fu_274_p1 );

    SC_METHOD(thread_not_do_cos_i_fu_624_p0);
    sensitive << ( do_cos );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_not_do_cos_i_fu_624_p2);
    sensitive << ( not_do_cos_i_fu_624_p0 );

    SC_METHOD(thread_not_or_cond_demorgan_fu_1044_p2);
    sensitive << ( tmp_7_reg_1147 );
    sensitive << ( tmp_6_reg_1205 );

    SC_METHOD(thread_not_or_cond_fu_1048_p2);
    sensitive << ( not_or_cond_demorgan_fu_1044_p2 );

    SC_METHOD(thread_not_tmp_s_fu_1011_p2);
    sensitive << ( tmp_8_reg_1211 );

    SC_METHOD(thread_or_cond_fu_1000_p2);
    sensitive << ( tmp_7_reg_1147 );
    sensitive << ( tmp_6_reg_1205 );

    SC_METHOD(thread_p_Ex_V_ret_fu_857_p3);
    sensitive << ( Ex_V_reg_1193 );
    sensitive << ( cos_basis_reg_1393 );

    SC_METHOD(thread_p_Result_1_cast_fu_1054_p3);
    sensitive << ( not_or_cond_fu_1048_p2 );

    SC_METHOD(thread_p_Result_20_fu_358_p3);
    sensitive << ( loc_V_1_reg_1110 );

    SC_METHOD(thread_p_Result_21_fu_435_p3);
    sensitive << ( p_Result_i2_i_reg_1175 );

    SC_METHOD(thread_p_Result_22_fu_442_p4);
    sensitive << ( p_Result_21_fu_435_p3 );

    SC_METHOD(thread_p_Result_23_fu_452_p3);
    sensitive << ( p_Result_22_fu_442_p4 );

    SC_METHOD(thread_p_Result_24_fu_636_p3);
    sensitive << ( p_Result_i_reg_1219 );
    sensitive << ( sin_basis_fu_630_p2 );

    SC_METHOD(thread_p_Result_25_fu_889_p3);
    sensitive << ( p_Val2_25_fu_885_p1 );

    SC_METHOD(thread_p_Result_26_fu_911_p3);
    sensitive << ( p_Result_19_reg_1097 );
    sensitive << ( p_Val2_29_reg_1164 );

    SC_METHOD(thread_p_Result_27_fu_1085_p4);
    sensitive << ( ret_V_6_reg_1435 );
    sensitive << ( ret_V_7_reg_1440 );
    sensitive << ( p_Result_s_49_fu_1079_p3 );

    SC_METHOD(thread_p_Result_i_i_fu_320_p4);
    sensitive << ( addr_V_fu_312_p3 );

    SC_METHOD(thread_p_Result_s_47_fu_1021_p3);
    sensitive << ( tmp_9_fu_1016_p2 );
    sensitive << ( not_tmp_s_fu_1011_p2 );
    sensitive << ( p_Result_25_fu_889_p3 );

    SC_METHOD(thread_p_Result_s_48_fu_1029_p3);
    sensitive << ( tmp_8_reg_1211 );
    sensitive << ( loc_V_2_fu_897_p4 );

    SC_METHOD(thread_p_Result_s_49_fu_1079_p3);
    sensitive << ( or_cond_reg_1425 );
    sensitive << ( p_Result_s_47_reg_1430 );
    sensitive << ( p_Result_s_fu_1075_p2 );

    SC_METHOD(thread_p_Result_s_fu_1075_p2);
    sensitive << ( p_Result_19_reg_1097 );
    sensitive << ( not_do_cos_i_reg_1253 );

    SC_METHOD(thread_p_Val2_11_fu_418_p3);
    sensitive << ( p_Val2_8_reg_1153 );
    sensitive << ( tmp_14_fu_409_p1 );
    sensitive << ( p_Val2_i_fu_413_p2 );

    SC_METHOD(thread_p_Val2_13_fu_487_p2);
    sensitive << ( p_Val2_11_reg_1170 );
    sensitive << ( tmp_19_i_fu_484_p1 );

    SC_METHOD(thread_p_Val2_14_fu_563_p3);
    sensitive << ( isNeg_reg_1199 );
    sensitive << ( tmp_26_i_fu_553_p2 );
    sensitive << ( tmp_27_i_fu_558_p2 );

    SC_METHOD(thread_p_Val2_15_fu_580_p1);
    sensitive << ( p_Val2_14_fu_563_p3 );

    SC_METHOD(thread_p_Val2_20_fu_737_p3);
    sensitive << ( p_Val2_19_reg_1343 );

    SC_METHOD(thread_p_Val2_21_fu_785_p2);
    sensitive << ( tmp_43_i_fu_778_p1 );
    sensitive << ( tmp_44_i_fu_782_p1 );

    SC_METHOD(thread_p_Val2_22_fu_794_p2);
    sensitive << ( p_Val2_21_fu_785_p2 );
    sensitive << ( tmp_46_i_cast_fu_791_p1 );

    SC_METHOD(thread_p_Val2_23_fu_824_p2);
    sensitive << ( p_Val2_22_reg_1383 );
    sensitive << ( tmp_48_i_cast_fu_821_p1 );

    SC_METHOD(thread_p_Val2_25_fu_885_p1);
    sensitive << ( grp_scaled_fixed2ieee_fu_268_ap_return );

    SC_METHOD(thread_p_Val2_29_fu_403_p3);
    sensitive << ( closepath_reg_1116 );
    sensitive << ( tmp_18_i_reg_1159 );

    SC_METHOD(thread_p_Val2_4_fu_762_p0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( p_Val2_4_fu_762_p00 );

    SC_METHOD(thread_p_Val2_4_fu_762_p00);
    sensitive << ( tmp_40_i_reg_1338 );

    SC_METHOD(thread_p_Val2_4_fu_762_p1);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( p_Val2_4_fu_762_p10 );

    SC_METHOD(thread_p_Val2_4_fu_762_p10);
    sensitive << ( fourth_order_double_16_reg_1363 );

    SC_METHOD(thread_p_Val2_4_fu_762_p2);
    sensitive << ( p_Val2_4_fu_762_p0 );
    sensitive << ( p_Val2_4_fu_762_p1 );

    SC_METHOD(thread_p_Val2_i_fu_413_p2);
    sensitive << ( p_Val2_8_reg_1153 );

    SC_METHOD(thread_p_Val2_s_fu_274_p1);
    sensitive << ( t_in );

    SC_METHOD(thread_p_cast_cast_fu_1004_p0);
    sensitive << ( do_cos );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_p_cast_cast_fu_1004_p3);
    sensitive << ( p_cast_cast_fu_1004_p0 );

    SC_METHOD(thread_r_V_3_fu_832_p2);
    sensitive << ( p_Val2_23_fu_824_p2 );
    sensitive << ( tmp_50_i_cast_fu_829_p1 );

    SC_METHOD(thread_r_V_4_fu_342_p2);
    sensitive << ( ref_4oPi_table_256_V_q0 );
    sensitive << ( tmp_7_i_i_fu_339_p1 );

    SC_METHOD(thread_r_V_fu_878_p2);
    sensitive << ( rhs_V_fu_874_p1 );

    SC_METHOD(thread_ref_4oPi_table_256_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_5_i_i_fu_330_p1 );

    SC_METHOD(thread_ref_4oPi_table_256_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ret_V_6_fu_1036_p3);
    sensitive << ( or_cond_fu_1000_p2 );
    sensitive << ( p_cast_cast_fu_1004_p3 );
    sensitive << ( p_Result_s_48_fu_1029_p3 );

    SC_METHOD(thread_ret_V_7_fu_1067_p3);
    sensitive << ( tmp_10_fu_1062_p2 );
    sensitive << ( p_Result_1_cast_fu_1054_p3 );
    sensitive << ( loc_V_3_fu_907_p1 );

    SC_METHOD(thread_rhs_V_fu_874_p1);
    sensitive << ( p_Ex_V_ret_fu_857_p3 );

    SC_METHOD(thread_sh_assign_2_cast_fu_545_p1);
    sensitive << ( sh_assign_fu_538_p3 );

    SC_METHOD(thread_sh_assign_fu_538_p3);
    sensitive << ( isNeg_reg_1199 );
    sensitive << ( sh_cast_fu_529_p1 );
    sensitive << ( tmp_24_i_fu_532_p2 );

    SC_METHOD(thread_sh_cast_fu_529_p1);
    sensitive << ( Ex_V_reg_1193 );

    SC_METHOD(thread_sin_basis_fu_630_p2);
    sensitive << ( tmp_fu_594_p10 );
    sensitive << ( not_do_cos_i_fu_624_p2 );

    SC_METHOD(thread_storemerge_i_fu_477_p3);
    sensitive << ( closepath_reg_1116 );
    sensitive << ( tmp_i_fu_472_p2 );

    SC_METHOD(thread_tmp_10_fu_1062_p2);
    sensitive << ( tmp_8_reg_1211 );
    sensitive << ( or_cond_fu_1000_p2 );

    SC_METHOD(thread_tmp_13_fu_335_p1);
    sensitive << ( addr_V_fu_312_p3 );

    SC_METHOD(thread_tmp_14_fu_409_p1);
    sensitive << ( p_Val2_29_fu_403_p3 );

    SC_METHOD(thread_tmp_19_i_fu_484_p1);
    sensitive << ( Mx_zeros_V_reg_1180 );

    SC_METHOD(thread_tmp_22_i_fu_502_p1);
    sensitive << ( Mx_zeros_V_reg_1180 );

    SC_METHOD(thread_tmp_24_i_fu_532_p2);
    sensitive << ( sh_cast_fu_529_p1 );

    SC_METHOD(thread_tmp_25_i_fu_549_p1);
    sensitive << ( sh_assign_2_cast_fu_545_p1 );

    SC_METHOD(thread_tmp_26_i_fu_553_p2);
    sensitive << ( Mx_V_reg_1186 );
    sensitive << ( tmp_25_i_fu_549_p1 );

    SC_METHOD(thread_tmp_27_i_fu_558_p2);
    sensitive << ( Mx_V_reg_1186 );
    sensitive << ( tmp_25_i_fu_549_p1 );

    SC_METHOD(thread_tmp_41_i_fu_643_p1);
    sensitive << ( p_Result_24_fu_636_p3 );

    SC_METHOD(thread_tmp_43_i_fu_778_p1);
    sensitive << ( p_Val2_20_fu_737_p3 );

    SC_METHOD(thread_tmp_44_i_fu_782_p1);
    sensitive << ( tmp_6_i_reg_1348 );

    SC_METHOD(thread_tmp_46_i_cast_fu_791_p1);
    sensitive << ( tmp_8_i_reg_1353 );

    SC_METHOD(thread_tmp_48_i_cast_fu_821_p1);
    sensitive << ( tmp_1_reg_1388 );

    SC_METHOD(thread_tmp_50_i_cast_fu_829_p1);
    sensitive << ( tmp_2_reg_1378 );

    SC_METHOD(thread_tmp_5_fu_993_p3);
    sensitive << ( cos_basis_reg_1393 );
    sensitive << ( tmp_3_fu_917_p18 );
    sensitive << ( tmp_4_fu_955_p18 );

    SC_METHOD(thread_tmp_5_i_i_fu_330_p1);
    sensitive << ( p_Result_i_i_fu_320_p4 );

    SC_METHOD(thread_tmp_6_fu_519_p2);
    sensitive << ( loc_V_reg_1103 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_tmp_7_fu_378_p2);
    sensitive << ( loc_V_1_reg_1110 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_tmp_7_i_i_fu_339_p1);
    sensitive << ( tmp_13_reg_1127 );

    SC_METHOD(thread_tmp_8_fu_524_p2);
    sensitive << ( loc_V_reg_1103 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_tmp_9_fu_1016_p2);
    sensitive << ( tmp_8_reg_1211 );
    sensitive << ( tmp_5_fu_993_p3 );

    SC_METHOD(thread_tmp_i3_i_fu_460_p3);
    sensitive << ( p_Result_23_fu_452_p3 );

    SC_METHOD(thread_tmp_i_fu_472_p2);
    sensitive << ( loc_V_reg_1103 );

    SC_METHOD(thread_tmp_s_fu_810_p2);
    sensitive << ( tmp_reg_1240 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( grp_scaled_fixed2ieee_fu_268_ap_done );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    ap_CS_fsm = "0000000000000000000000001";
    grp_scaled_fixed2ieee_fu_268_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sin_or_cos_double_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, t_in, "(port)t_in");
    sc_trace(mVcdFile, do_cos, "(port)do_cos");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ref_4oPi_table_256_V_address0, "ref_4oPi_table_256_V_address0");
    sc_trace(mVcdFile, ref_4oPi_table_256_V_ce0, "ref_4oPi_table_256_V_ce0");
    sc_trace(mVcdFile, ref_4oPi_table_256_V_q0, "ref_4oPi_table_256_V_q0");
    sc_trace(mVcdFile, fourth_order_double_4_address0, "fourth_order_double_4_address0");
    sc_trace(mVcdFile, fourth_order_double_4_ce0, "fourth_order_double_4_ce0");
    sc_trace(mVcdFile, fourth_order_double_4_q0, "fourth_order_double_4_q0");
    sc_trace(mVcdFile, fourth_order_double_5_address0, "fourth_order_double_5_address0");
    sc_trace(mVcdFile, fourth_order_double_5_ce0, "fourth_order_double_5_ce0");
    sc_trace(mVcdFile, fourth_order_double_5_q0, "fourth_order_double_5_q0");
    sc_trace(mVcdFile, fourth_order_double_6_address0, "fourth_order_double_6_address0");
    sc_trace(mVcdFile, fourth_order_double_6_ce0, "fourth_order_double_6_ce0");
    sc_trace(mVcdFile, fourth_order_double_6_q0, "fourth_order_double_6_q0");
    sc_trace(mVcdFile, fourth_order_double_7_address0, "fourth_order_double_7_address0");
    sc_trace(mVcdFile, fourth_order_double_7_ce0, "fourth_order_double_7_ce0");
    sc_trace(mVcdFile, fourth_order_double_7_q0, "fourth_order_double_7_q0");
    sc_trace(mVcdFile, fourth_order_double_s_address0, "fourth_order_double_s_address0");
    sc_trace(mVcdFile, fourth_order_double_s_ce0, "fourth_order_double_s_ce0");
    sc_trace(mVcdFile, fourth_order_double_s_q0, "fourth_order_double_s_q0");
    sc_trace(mVcdFile, p_Result_19_reg_1097, "p_Result_19_reg_1097");
    sc_trace(mVcdFile, loc_V_fu_286_p4, "loc_V_fu_286_p4");
    sc_trace(mVcdFile, loc_V_reg_1103, "loc_V_reg_1103");
    sc_trace(mVcdFile, loc_V_1_fu_296_p1, "loc_V_1_fu_296_p1");
    sc_trace(mVcdFile, loc_V_1_reg_1110, "loc_V_1_reg_1110");
    sc_trace(mVcdFile, closepath_fu_300_p2, "closepath_fu_300_p2");
    sc_trace(mVcdFile, closepath_reg_1116, "closepath_reg_1116");
    sc_trace(mVcdFile, tmp_13_fu_335_p1, "tmp_13_fu_335_p1");
    sc_trace(mVcdFile, tmp_13_reg_1127, "tmp_13_reg_1127");
    sc_trace(mVcdFile, ret_V_reg_1132, "ret_V_reg_1132");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_7_fu_378_p2, "tmp_7_fu_378_p2");
    sc_trace(mVcdFile, tmp_7_reg_1147, "tmp_7_reg_1147");
    sc_trace(mVcdFile, p_Val2_8_reg_1153, "p_Val2_8_reg_1153");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_18_i_reg_1159, "tmp_18_i_reg_1159");
    sc_trace(mVcdFile, p_Val2_29_fu_403_p3, "p_Val2_29_fu_403_p3");
    sc_trace(mVcdFile, p_Val2_29_reg_1164, "p_Val2_29_reg_1164");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, p_Val2_11_fu_418_p3, "p_Val2_11_fu_418_p3");
    sc_trace(mVcdFile, p_Val2_11_reg_1170, "p_Val2_11_reg_1170");
    sc_trace(mVcdFile, p_Result_i2_i_reg_1175, "p_Result_i2_i_reg_1175");
    sc_trace(mVcdFile, Mx_zeros_V_fu_468_p1, "Mx_zeros_V_fu_468_p1");
    sc_trace(mVcdFile, Mx_zeros_V_reg_1180, "Mx_zeros_V_reg_1180");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, Mx_V_reg_1186, "Mx_V_reg_1186");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, Ex_V_fu_505_p2, "Ex_V_fu_505_p2");
    sc_trace(mVcdFile, Ex_V_reg_1193, "Ex_V_reg_1193");
    sc_trace(mVcdFile, isNeg_reg_1199, "isNeg_reg_1199");
    sc_trace(mVcdFile, tmp_6_fu_519_p2, "tmp_6_fu_519_p2");
    sc_trace(mVcdFile, tmp_6_reg_1205, "tmp_6_reg_1205");
    sc_trace(mVcdFile, tmp_8_fu_524_p2, "tmp_8_fu_524_p2");
    sc_trace(mVcdFile, tmp_8_reg_1211, "tmp_8_reg_1211");
    sc_trace(mVcdFile, p_Result_i_reg_1219, "p_Result_i_reg_1219");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, p_Val2_15_fu_580_p1, "p_Val2_15_fu_580_p1");
    sc_trace(mVcdFile, p_Val2_15_reg_1224, "p_Val2_15_reg_1224");
    sc_trace(mVcdFile, tmp_i1_reg_1229, "tmp_i1_reg_1229");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_fu_594_p10, "tmp_fu_594_p10");
    sc_trace(mVcdFile, tmp_reg_1240, "tmp_reg_1240");
    sc_trace(mVcdFile, OP1_V_fu_615_p1, "OP1_V_fu_615_p1");
    sc_trace(mVcdFile, OP1_V_reg_1246, "OP1_V_reg_1246");
    sc_trace(mVcdFile, not_do_cos_i_fu_624_p2, "not_do_cos_i_fu_624_p2");
    sc_trace(mVcdFile, not_do_cos_i_reg_1253, "not_do_cos_i_reg_1253");
    sc_trace(mVcdFile, tmp_41_i_fu_643_p1, "tmp_41_i_fu_643_p1");
    sc_trace(mVcdFile, tmp_41_i_reg_1258, "tmp_41_i_reg_1258");
    sc_trace(mVcdFile, tmp_36_i_reg_1275, "tmp_36_i_reg_1275");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, fourth_order_double_10_reg_1281, "fourth_order_double_10_reg_1281");
    sc_trace(mVcdFile, fourth_order_double_12_reg_1286, "fourth_order_double_12_reg_1286");
    sc_trace(mVcdFile, OP2_V_fu_659_p1, "OP2_V_fu_659_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, tmp_38_i_reg_1333, "tmp_38_i_reg_1333");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, tmp_40_i_reg_1338, "tmp_40_i_reg_1338");
    sc_trace(mVcdFile, p_Val2_19_reg_1343, "p_Val2_19_reg_1343");
    sc_trace(mVcdFile, tmp_6_i_reg_1348, "tmp_6_i_reg_1348");
    sc_trace(mVcdFile, tmp_8_i_reg_1353, "tmp_8_i_reg_1353");
    sc_trace(mVcdFile, fourth_order_double_14_reg_1358, "fourth_order_double_14_reg_1358");
    sc_trace(mVcdFile, fourth_order_double_16_reg_1363, "fourth_order_double_16_reg_1363");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, tmp_2_reg_1378, "tmp_2_reg_1378");
    sc_trace(mVcdFile, p_Val2_22_fu_794_p2, "p_Val2_22_fu_794_p2");
    sc_trace(mVcdFile, p_Val2_22_reg_1383, "p_Val2_22_reg_1383");
    sc_trace(mVcdFile, tmp_1_reg_1388, "tmp_1_reg_1388");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, cos_basis_fu_815_p3, "cos_basis_fu_815_p3");
    sc_trace(mVcdFile, cos_basis_reg_1393, "cos_basis_reg_1393");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, r_V_3_fu_832_p2, "r_V_3_fu_832_p2");
    sc_trace(mVcdFile, r_V_3_reg_1400, "r_V_3_reg_1400");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, result_V_reg_1415, "result_V_reg_1415");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, r_V_fu_878_p2, "r_V_fu_878_p2");
    sc_trace(mVcdFile, r_V_reg_1420, "r_V_reg_1420");
    sc_trace(mVcdFile, or_cond_fu_1000_p2, "or_cond_fu_1000_p2");
    sc_trace(mVcdFile, or_cond_reg_1425, "or_cond_reg_1425");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_268_ap_idle, "grp_scaled_fixed2ieee_fu_268_ap_idle");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_268_ap_ready, "grp_scaled_fixed2ieee_fu_268_ap_ready");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_268_ap_done, "grp_scaled_fixed2ieee_fu_268_ap_done");
    sc_trace(mVcdFile, p_Result_s_47_fu_1021_p3, "p_Result_s_47_fu_1021_p3");
    sc_trace(mVcdFile, p_Result_s_47_reg_1430, "p_Result_s_47_reg_1430");
    sc_trace(mVcdFile, ret_V_6_fu_1036_p3, "ret_V_6_fu_1036_p3");
    sc_trace(mVcdFile, ret_V_6_reg_1435, "ret_V_6_reg_1435");
    sc_trace(mVcdFile, ret_V_7_fu_1067_p3, "ret_V_7_fu_1067_p3");
    sc_trace(mVcdFile, ret_V_7_reg_1440, "ret_V_7_reg_1440");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_268_ap_start, "grp_scaled_fixed2ieee_fu_268_ap_start");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_268_ap_return, "grp_scaled_fixed2ieee_fu_268_ap_return");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_268_ap_start_reg, "grp_scaled_fixed2ieee_fu_268_ap_start_reg");
    sc_trace(mVcdFile, tmp_5_i_i_fu_330_p1, "tmp_5_i_i_fu_330_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_274_p1, "p_Val2_s_fu_274_p1");
    sc_trace(mVcdFile, expv_op_fu_306_p2, "expv_op_fu_306_p2");
    sc_trace(mVcdFile, addr_V_fu_312_p3, "addr_V_fu_312_p3");
    sc_trace(mVcdFile, p_Result_i_i_fu_320_p4, "p_Result_i_i_fu_320_p4");
    sc_trace(mVcdFile, tmp_7_i_i_fu_339_p1, "tmp_7_i_i_fu_339_p1");
    sc_trace(mVcdFile, r_V_4_fu_342_p2, "r_V_4_fu_342_p2");
    sc_trace(mVcdFile, p_Result_20_fu_358_p3, "p_Result_20_fu_358_p3");
    sc_trace(mVcdFile, grp_fu_372_p0, "grp_fu_372_p0");
    sc_trace(mVcdFile, grp_fu_372_p1, "grp_fu_372_p1");
    sc_trace(mVcdFile, grp_fu_372_p2, "grp_fu_372_p2");
    sc_trace(mVcdFile, tmp_14_fu_409_p1, "tmp_14_fu_409_p1");
    sc_trace(mVcdFile, p_Val2_i_fu_413_p2, "p_Val2_i_fu_413_p2");
    sc_trace(mVcdFile, p_Result_21_fu_435_p3, "p_Result_21_fu_435_p3");
    sc_trace(mVcdFile, p_Result_22_fu_442_p4, "p_Result_22_fu_442_p4");
    sc_trace(mVcdFile, p_Result_23_fu_452_p3, "p_Result_23_fu_452_p3");
    sc_trace(mVcdFile, tmp_i3_i_fu_460_p3, "tmp_i3_i_fu_460_p3");
    sc_trace(mVcdFile, tmp_i_fu_472_p2, "tmp_i_fu_472_p2");
    sc_trace(mVcdFile, tmp_19_i_fu_484_p1, "tmp_19_i_fu_484_p1");
    sc_trace(mVcdFile, p_Val2_13_fu_487_p2, "p_Val2_13_fu_487_p2");
    sc_trace(mVcdFile, storemerge_i_fu_477_p3, "storemerge_i_fu_477_p3");
    sc_trace(mVcdFile, tmp_22_i_fu_502_p1, "tmp_22_i_fu_502_p1");
    sc_trace(mVcdFile, sh_cast_fu_529_p1, "sh_cast_fu_529_p1");
    sc_trace(mVcdFile, tmp_24_i_fu_532_p2, "tmp_24_i_fu_532_p2");
    sc_trace(mVcdFile, sh_assign_fu_538_p3, "sh_assign_fu_538_p3");
    sc_trace(mVcdFile, sh_assign_2_cast_fu_545_p1, "sh_assign_2_cast_fu_545_p1");
    sc_trace(mVcdFile, tmp_25_i_fu_549_p1, "tmp_25_i_fu_549_p1");
    sc_trace(mVcdFile, tmp_26_i_fu_553_p2, "tmp_26_i_fu_553_p2");
    sc_trace(mVcdFile, tmp_27_i_fu_558_p2, "tmp_27_i_fu_558_p2");
    sc_trace(mVcdFile, p_Val2_14_fu_563_p3, "p_Val2_14_fu_563_p3");
    sc_trace(mVcdFile, grp_fu_618_p0, "grp_fu_618_p0");
    sc_trace(mVcdFile, grp_fu_618_p1, "grp_fu_618_p1");
    sc_trace(mVcdFile, not_do_cos_i_fu_624_p0, "not_do_cos_i_fu_624_p0");
    sc_trace(mVcdFile, sin_basis_fu_630_p2, "sin_basis_fu_630_p2");
    sc_trace(mVcdFile, p_Result_24_fu_636_p3, "p_Result_24_fu_636_p3");
    sc_trace(mVcdFile, grp_fu_618_p2, "grp_fu_618_p2");
    sc_trace(mVcdFile, grp_fu_662_p0, "grp_fu_662_p0");
    sc_trace(mVcdFile, grp_fu_662_p1, "grp_fu_662_p1");
    sc_trace(mVcdFile, grp_fu_667_p0, "grp_fu_667_p0");
    sc_trace(mVcdFile, grp_fu_667_p1, "grp_fu_667_p1");
    sc_trace(mVcdFile, grp_fu_679_p0, "grp_fu_679_p0");
    sc_trace(mVcdFile, grp_fu_691_p0, "grp_fu_691_p0");
    sc_trace(mVcdFile, grp_fu_662_p2, "grp_fu_662_p2");
    sc_trace(mVcdFile, grp_fu_667_p2, "grp_fu_667_p2");
    sc_trace(mVcdFile, grp_fu_679_p2, "grp_fu_679_p2");
    sc_trace(mVcdFile, grp_fu_691_p2, "grp_fu_691_p2");
    sc_trace(mVcdFile, grp_fu_750_p0, "grp_fu_750_p0");
    sc_trace(mVcdFile, grp_fu_750_p1, "grp_fu_750_p1");
    sc_trace(mVcdFile, p_Val2_4_fu_762_p0, "p_Val2_4_fu_762_p0");
    sc_trace(mVcdFile, p_Val2_4_fu_762_p1, "p_Val2_4_fu_762_p1");
    sc_trace(mVcdFile, p_Val2_4_fu_762_p2, "p_Val2_4_fu_762_p2");
    sc_trace(mVcdFile, p_Val2_20_fu_737_p3, "p_Val2_20_fu_737_p3");
    sc_trace(mVcdFile, tmp_43_i_fu_778_p1, "tmp_43_i_fu_778_p1");
    sc_trace(mVcdFile, tmp_44_i_fu_782_p1, "tmp_44_i_fu_782_p1");
    sc_trace(mVcdFile, p_Val2_21_fu_785_p2, "p_Val2_21_fu_785_p2");
    sc_trace(mVcdFile, tmp_46_i_cast_fu_791_p1, "tmp_46_i_cast_fu_791_p1");
    sc_trace(mVcdFile, grp_fu_750_p2, "grp_fu_750_p2");
    sc_trace(mVcdFile, cos_basis_fu_815_p0, "cos_basis_fu_815_p0");
    sc_trace(mVcdFile, tmp_s_fu_810_p2, "tmp_s_fu_810_p2");
    sc_trace(mVcdFile, tmp_48_i_cast_fu_821_p1, "tmp_48_i_cast_fu_821_p1");
    sc_trace(mVcdFile, p_Val2_23_fu_824_p2, "p_Val2_23_fu_824_p2");
    sc_trace(mVcdFile, tmp_50_i_cast_fu_829_p1, "tmp_50_i_cast_fu_829_p1");
    sc_trace(mVcdFile, Mx_V_read_assign_fu_838_p3, "Mx_V_read_assign_fu_838_p3");
    sc_trace(mVcdFile, grp_fu_851_p1, "grp_fu_851_p1");
    sc_trace(mVcdFile, grp_fu_851_p2, "grp_fu_851_p2");
    sc_trace(mVcdFile, p_Ex_V_ret_fu_857_p3, "p_Ex_V_ret_fu_857_p3");
    sc_trace(mVcdFile, rhs_V_fu_874_p1, "rhs_V_fu_874_p1");
    sc_trace(mVcdFile, p_Val2_25_fu_885_p1, "p_Val2_25_fu_885_p1");
    sc_trace(mVcdFile, p_Result_26_fu_911_p3, "p_Result_26_fu_911_p3");
    sc_trace(mVcdFile, tmp_3_fu_917_p18, "tmp_3_fu_917_p18");
    sc_trace(mVcdFile, tmp_4_fu_955_p18, "tmp_4_fu_955_p18");
    sc_trace(mVcdFile, p_cast_cast_fu_1004_p0, "p_cast_cast_fu_1004_p0");
    sc_trace(mVcdFile, tmp_5_fu_993_p3, "tmp_5_fu_993_p3");
    sc_trace(mVcdFile, tmp_9_fu_1016_p2, "tmp_9_fu_1016_p2");
    sc_trace(mVcdFile, not_tmp_s_fu_1011_p2, "not_tmp_s_fu_1011_p2");
    sc_trace(mVcdFile, p_Result_25_fu_889_p3, "p_Result_25_fu_889_p3");
    sc_trace(mVcdFile, loc_V_2_fu_897_p4, "loc_V_2_fu_897_p4");
    sc_trace(mVcdFile, p_cast_cast_fu_1004_p3, "p_cast_cast_fu_1004_p3");
    sc_trace(mVcdFile, p_Result_s_48_fu_1029_p3, "p_Result_s_48_fu_1029_p3");
    sc_trace(mVcdFile, not_or_cond_demorgan_fu_1044_p2, "not_or_cond_demorgan_fu_1044_p2");
    sc_trace(mVcdFile, not_or_cond_fu_1048_p2, "not_or_cond_fu_1048_p2");
    sc_trace(mVcdFile, tmp_10_fu_1062_p2, "tmp_10_fu_1062_p2");
    sc_trace(mVcdFile, p_Result_1_cast_fu_1054_p3, "p_Result_1_cast_fu_1054_p3");
    sc_trace(mVcdFile, loc_V_3_fu_907_p1, "loc_V_3_fu_907_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, p_Result_s_fu_1075_p2, "p_Result_s_fu_1075_p2");
    sc_trace(mVcdFile, p_Result_s_49_fu_1079_p3, "p_Result_s_49_fu_1079_p3");
    sc_trace(mVcdFile, p_Result_27_fu_1085_p4, "p_Result_27_fu_1085_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_372_p00, "grp_fu_372_p00");
    sc_trace(mVcdFile, grp_fu_372_p10, "grp_fu_372_p10");
    sc_trace(mVcdFile, grp_fu_679_p00, "grp_fu_679_p00");
    sc_trace(mVcdFile, grp_fu_691_p00, "grp_fu_691_p00");
    sc_trace(mVcdFile, grp_fu_750_p00, "grp_fu_750_p00");
    sc_trace(mVcdFile, grp_fu_750_p10, "grp_fu_750_p10");
    sc_trace(mVcdFile, grp_fu_851_p10, "grp_fu_851_p10");
    sc_trace(mVcdFile, p_Val2_4_fu_762_p00, "p_Val2_4_fu_762_p00");
    sc_trace(mVcdFile, p_Val2_4_fu_762_p10, "p_Val2_4_fu_762_p10");
#endif

    }
}

sin_or_cos_double_s::~sin_or_cos_double_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete ref_4oPi_table_256_V_U;
    delete fourth_order_double_4_U;
    delete fourth_order_double_5_U;
    delete fourth_order_double_6_U;
    delete fourth_order_double_7_U;
    delete fourth_order_double_s_U;
    delete grp_scaled_fixed2ieee_fu_268;
    delete convert_mul_170nsibs_U6;
    delete convert_mux_83_1_jbC_U7;
    delete convert_mul_49ns_kbM_U8;
    delete convert_mul_49ns_kbM_U9;
    delete convert_mul_49ns_kbM_U10;
    delete convert_mul_56ns_lbW_U11;
    delete convert_mul_49ns_mb6_U12;
    delete convert_mul_42ns_ncg_U13;
    delete convert_mul_64s_6ocq_U14;
    delete convert_mux_164_1pcA_U15;
    delete convert_mux_164_1pcA_U16;
}

void sin_or_cos_double_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void sin_or_cos_double_s::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv1_0;
}

void sin_or_cos_double_s::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv1_1;
}

void sin_or_cos_double_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_scaled_fixed2ieee_fu_268_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
            grp_scaled_fixed2ieee_fu_268_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_scaled_fixed2ieee_fu_268_ap_ready.read())) {
            grp_scaled_fixed2ieee_fu_268_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        Ex_V_reg_1193 = Ex_V_fu_505_p2.read();
        Mx_V_reg_1186 = p_Val2_13_fu_487_p2.read().range(123, 61);
        isNeg_reg_1199 = Ex_V_fu_505_p2.read().range(10, 10);
        tmp_6_reg_1205 = tmp_6_fu_519_p2.read();
        tmp_8_reg_1211 = tmp_8_fu_524_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        Mx_zeros_V_reg_1180 = Mx_zeros_V_fu_468_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        OP1_V_reg_1246 = OP1_V_fu_615_p1.read();
        not_do_cos_i_reg_1253 = not_do_cos_i_fu_624_p2.read();
        tmp_41_i_reg_1258 = tmp_41_i_fu_643_p1.read();
        tmp_reg_1240 = tmp_fu_594_p10.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        closepath_reg_1116 = closepath_fu_300_p2.read();
        loc_V_1_reg_1110 = loc_V_1_fu_296_p1.read();
        loc_V_reg_1103 = p_Val2_s_fu_274_p1.read().range(62, 52);
        p_Result_19_reg_1097 = p_Val2_s_fu_274_p1.read().range(63, 63);
        tmp_13_reg_1127 = tmp_13_fu_335_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        cos_basis_reg_1393 = cos_basis_fu_815_p3.read();
        r_V_3_reg_1400 = r_V_3_fu_832_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        fourth_order_double_10_reg_1281 = fourth_order_double_5_q0.read();
        fourth_order_double_12_reg_1286 = fourth_order_double_6_q0.read();
        tmp_36_i_reg_1275 = grp_fu_618_p2.read().range(97, 49);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        fourth_order_double_14_reg_1358 = fourth_order_double_7_q0.read();
        fourth_order_double_16_reg_1363 = fourth_order_double_s_q0.read();
        p_Val2_19_reg_1343 = fourth_order_double_4_q0.read();
        tmp_38_i_reg_1333 = grp_fu_662_p2.read().range(97, 56);
        tmp_40_i_reg_1338 = grp_fu_667_p2.read().range(97, 63);
        tmp_6_i_reg_1348 = grp_fu_679_p2.read().range(107, 52);
        tmp_8_i_reg_1353 = grp_fu_691_p2.read().range(92, 45);
    }
    if ((esl_seteq<1,1,1>(grp_scaled_fixed2ieee_fu_268_ap_done.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()))) {
        or_cond_reg_1425 = or_cond_fu_1000_p2.read();
        p_Result_s_47_reg_1430 = p_Result_s_47_fu_1021_p3.read();
        ret_V_6_reg_1435 = ret_V_6_fu_1036_p3.read();
        ret_V_7_reg_1440 = ret_V_7_fu_1067_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        p_Result_i2_i_reg_1175 = p_Val2_11_fu_418_p3.read().range(123, 63);
        p_Val2_11_reg_1170 = p_Val2_11_fu_418_p3.read();
        p_Val2_29_reg_1164 = p_Val2_29_fu_403_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        p_Result_i_reg_1219 = p_Val2_14_fu_563_p3.read().range(62, 56);
        p_Val2_15_reg_1224 = p_Val2_15_fu_580_p1.read();
        tmp_i1_reg_1229 = p_Val2_14_fu_563_p3.read().range(55, 7);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        p_Val2_22_reg_1383 = p_Val2_22_fu_794_p2.read();
        tmp_2_reg_1378 = p_Val2_4_fu_762_p2.read().range(59, 31);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        p_Val2_8_reg_1153 = grp_fu_372_p2.read().range(166, 43);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        r_V_reg_1420 = r_V_fu_878_p2.read();
        result_V_reg_1415 = grp_fu_851_p2.read().range(125, 63);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        ret_V_reg_1132 = r_V_4_fu_342_p2.read().range(255, 86);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(closepath_reg_1116.read(), ap_const_lv1_0))) {
        tmp_18_i_reg_1159 = grp_fu_372_p2.read().range(169, 167);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        tmp_1_reg_1388 = grp_fu_750_p2.read().range(74, 38);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        tmp_7_reg_1147 = tmp_7_fu_378_p2.read();
    }
}

void sin_or_cos_double_s::thread_Ex_V_fu_505_p2() {
    Ex_V_fu_505_p2 = (!storemerge_i_fu_477_p3.read().is_01() || !tmp_22_i_fu_502_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(storemerge_i_fu_477_p3.read()) - sc_biguint<11>(tmp_22_i_fu_502_p1.read()));
}

void sin_or_cos_double_s::thread_Mx_V_read_assign_fu_838_p3() {
    Mx_V_read_assign_fu_838_p3 = (!cos_basis_reg_1393.read()[0].is_01())? sc_lv<63>(): ((cos_basis_reg_1393.read()[0].to_bool())? ap_const_lv63_7FFFFFFFFFFFFFFF: Mx_V_reg_1186.read());
}

void sin_or_cos_double_s::thread_Mx_zeros_V_fu_468_p1() {
    Mx_zeros_V_fu_468_p1 = tmp_i3_i_fu_460_p3.read().range(6-1, 0);
}

void sin_or_cos_double_s::thread_OP1_V_fu_615_p1() {
    OP1_V_fu_615_p1 = esl_zext<98,49>(tmp_i1_reg_1229.read());
}

void sin_or_cos_double_s::thread_OP2_V_fu_659_p1() {
    OP2_V_fu_659_p1 = esl_zext<98,49>(tmp_36_i_reg_1275.read());
}

void sin_or_cos_double_s::thread_addr_V_fu_312_p3() {
    addr_V_fu_312_p3 = (!closepath_fu_300_p2.read()[0].is_01())? sc_lv<11>(): ((closepath_fu_300_p2.read()[0].to_bool())? ap_const_lv11_4A: expv_op_fu_306_p2.read());
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void sin_or_cos_double_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_ap_return() {
    ap_return = p_Result_27_fu_1085_p4.read();
}

void sin_or_cos_double_s::thread_closepath_fu_300_p2() {
    closepath_fu_300_p2 = (!loc_V_fu_286_p4.read().is_01() || !ap_const_lv11_3FE.is_01())? sc_lv<1>(): (sc_biguint<11>(loc_V_fu_286_p4.read()) < sc_biguint<11>(ap_const_lv11_3FE));
}

void sin_or_cos_double_s::thread_cos_basis_fu_815_p0() {
    cos_basis_fu_815_p0 =  (sc_lv<1>) (do_cos.read());
}

void sin_or_cos_double_s::thread_cos_basis_fu_815_p3() {
    cos_basis_fu_815_p3 = (!cos_basis_fu_815_p0.read()[0].is_01())? sc_lv<1>(): ((cos_basis_fu_815_p0.read()[0].to_bool())? tmp_s_fu_810_p2.read(): tmp_reg_1240.read());
}

void sin_or_cos_double_s::thread_expv_op_fu_306_p2() {
    expv_op_fu_306_p2 = (!ap_const_lv11_44D.is_01() || !loc_V_fu_286_p4.read().is_01())? sc_lv<11>(): (sc_bigint<11>(ap_const_lv11_44D) + sc_biguint<11>(loc_V_fu_286_p4.read()));
}

void sin_or_cos_double_s::thread_fourth_order_double_4_address0() {
    fourth_order_double_4_address0 =  (sc_lv<8>) (tmp_41_i_reg_1258.read());
}

void sin_or_cos_double_s::thread_fourth_order_double_4_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        fourth_order_double_4_ce0 = ap_const_logic_1;
    } else {
        fourth_order_double_4_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_fourth_order_double_5_address0() {
    fourth_order_double_5_address0 =  (sc_lv<8>) (tmp_41_i_fu_643_p1.read());
}

void sin_or_cos_double_s::thread_fourth_order_double_5_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        fourth_order_double_5_ce0 = ap_const_logic_1;
    } else {
        fourth_order_double_5_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_fourth_order_double_6_address0() {
    fourth_order_double_6_address0 =  (sc_lv<8>) (tmp_41_i_fu_643_p1.read());
}

void sin_or_cos_double_s::thread_fourth_order_double_6_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        fourth_order_double_6_ce0 = ap_const_logic_1;
    } else {
        fourth_order_double_6_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_fourth_order_double_7_address0() {
    fourth_order_double_7_address0 =  (sc_lv<8>) (tmp_41_i_reg_1258.read());
}

void sin_or_cos_double_s::thread_fourth_order_double_7_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        fourth_order_double_7_ce0 = ap_const_logic_1;
    } else {
        fourth_order_double_7_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_fourth_order_double_s_address0() {
    fourth_order_double_s_address0 =  (sc_lv<8>) (tmp_41_i_reg_1258.read());
}

void sin_or_cos_double_s::thread_fourth_order_double_s_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        fourth_order_double_s_ce0 = ap_const_logic_1;
    } else {
        fourth_order_double_s_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_grp_fu_372_p0() {
    grp_fu_372_p0 =  (sc_lv<170>) (grp_fu_372_p00.read());
}

void sin_or_cos_double_s::thread_grp_fu_372_p00() {
    grp_fu_372_p00 = esl_zext<223,170>(ret_V_reg_1132.read());
}

void sin_or_cos_double_s::thread_grp_fu_372_p1() {
    grp_fu_372_p1 =  (sc_lv<53>) (grp_fu_372_p10.read());
}

void sin_or_cos_double_s::thread_grp_fu_372_p10() {
    grp_fu_372_p10 = esl_zext<223,53>(p_Result_20_fu_358_p3.read());
}

void sin_or_cos_double_s::thread_grp_fu_618_p0() {
    grp_fu_618_p0 =  (sc_lv<49>) (OP1_V_fu_615_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_618_p1() {
    grp_fu_618_p1 =  (sc_lv<49>) (OP1_V_fu_615_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_662_p0() {
    grp_fu_662_p0 =  (sc_lv<49>) (OP2_V_fu_659_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_662_p1() {
    grp_fu_662_p1 =  (sc_lv<49>) (OP1_V_reg_1246.read());
}

void sin_or_cos_double_s::thread_grp_fu_667_p0() {
    grp_fu_667_p0 =  (sc_lv<49>) (OP2_V_fu_659_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_667_p1() {
    grp_fu_667_p1 =  (sc_lv<49>) (OP2_V_fu_659_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_679_p0() {
    grp_fu_679_p0 =  (sc_lv<56>) (grp_fu_679_p00.read());
}

void sin_or_cos_double_s::thread_grp_fu_679_p00() {
    grp_fu_679_p00 = esl_zext<108,56>(p_Val2_15_reg_1224.read());
}

void sin_or_cos_double_s::thread_grp_fu_691_p0() {
    grp_fu_691_p0 =  (sc_lv<49>) (grp_fu_691_p00.read());
}

void sin_or_cos_double_s::thread_grp_fu_691_p00() {
    grp_fu_691_p00 = esl_zext<93,49>(tmp_36_i_reg_1275.read());
}

void sin_or_cos_double_s::thread_grp_fu_750_p0() {
    grp_fu_750_p0 =  (sc_lv<42>) (grp_fu_750_p00.read());
}

void sin_or_cos_double_s::thread_grp_fu_750_p00() {
    grp_fu_750_p00 = esl_zext<75,42>(tmp_38_i_reg_1333.read());
}

void sin_or_cos_double_s::thread_grp_fu_750_p1() {
    grp_fu_750_p1 =  (sc_lv<33>) (grp_fu_750_p10.read());
}

void sin_or_cos_double_s::thread_grp_fu_750_p10() {
    grp_fu_750_p10 = esl_zext<75,33>(fourth_order_double_14_reg_1358.read());
}

void sin_or_cos_double_s::thread_grp_fu_851_p1() {
    grp_fu_851_p1 =  (sc_lv<63>) (grp_fu_851_p10.read());
}

void sin_or_cos_double_s::thread_grp_fu_851_p10() {
    grp_fu_851_p10 = esl_zext<126,63>(Mx_V_read_assign_fu_838_p3.read());
}

void sin_or_cos_double_s::thread_grp_scaled_fixed2ieee_fu_268_ap_start() {
    grp_scaled_fixed2ieee_fu_268_ap_start = grp_scaled_fixed2ieee_fu_268_ap_start_reg.read();
}

void sin_or_cos_double_s::thread_loc_V_1_fu_296_p1() {
    loc_V_1_fu_296_p1 = p_Val2_s_fu_274_p1.read().range(52-1, 0);
}

void sin_or_cos_double_s::thread_loc_V_2_fu_897_p4() {
    loc_V_2_fu_897_p4 = p_Val2_25_fu_885_p1.read().range(62, 52);
}

void sin_or_cos_double_s::thread_loc_V_3_fu_907_p1() {
    loc_V_3_fu_907_p1 = p_Val2_25_fu_885_p1.read().range(52-1, 0);
}

void sin_or_cos_double_s::thread_loc_V_fu_286_p4() {
    loc_V_fu_286_p4 = p_Val2_s_fu_274_p1.read().range(62, 52);
}

void sin_or_cos_double_s::thread_not_do_cos_i_fu_624_p0() {
    not_do_cos_i_fu_624_p0 =  (sc_lv<1>) (do_cos.read());
}

void sin_or_cos_double_s::thread_not_do_cos_i_fu_624_p2() {
    not_do_cos_i_fu_624_p2 = (not_do_cos_i_fu_624_p0.read() ^ ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_not_or_cond_demorgan_fu_1044_p2() {
    not_or_cond_demorgan_fu_1044_p2 = (tmp_6_reg_1205.read() & tmp_7_reg_1147.read());
}

void sin_or_cos_double_s::thread_not_or_cond_fu_1048_p2() {
    not_or_cond_fu_1048_p2 = (not_or_cond_demorgan_fu_1044_p2.read() ^ ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_not_tmp_s_fu_1011_p2() {
    not_tmp_s_fu_1011_p2 = (tmp_8_reg_1211.read() ^ ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_or_cond_fu_1000_p2() {
    or_cond_fu_1000_p2 = (tmp_6_reg_1205.read() & tmp_7_reg_1147.read());
}

void sin_or_cos_double_s::thread_p_Ex_V_ret_fu_857_p3() {
    p_Ex_V_ret_fu_857_p3 = (!cos_basis_reg_1393.read()[0].is_01())? sc_lv<11>(): ((cos_basis_reg_1393.read()[0].to_bool())? ap_const_lv11_0: Ex_V_reg_1193.read());
}

void sin_or_cos_double_s::thread_p_Result_1_cast_fu_1054_p3() {
    p_Result_1_cast_fu_1054_p3 = (!not_or_cond_fu_1048_p2.read()[0].is_01())? sc_lv<52>(): ((not_or_cond_fu_1048_p2.read()[0].to_bool())? ap_const_lv52_FFFFFFFFFFFFF: ap_const_lv52_0);
}

void sin_or_cos_double_s::thread_p_Result_20_fu_358_p3() {
    p_Result_20_fu_358_p3 = esl_concat<1,52>(ap_const_lv1_1, loc_V_1_reg_1110.read());
}

void sin_or_cos_double_s::thread_p_Result_21_fu_435_p3() {
    p_Result_21_fu_435_p3 = esl_concat<61,1>(p_Result_i2_i_reg_1175.read(), ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_p_Result_22_fu_442_p4() {
    p_Result_22_fu_442_p4 = p_Result_21_fu_435_p3.read().range(0, 61);
}

void sin_or_cos_double_s::thread_p_Result_23_fu_452_p3() {
    p_Result_23_fu_452_p3 = esl_concat<2,62>(ap_const_lv2_3, p_Result_22_fu_442_p4.read());
}

void sin_or_cos_double_s::thread_p_Result_24_fu_636_p3() {
    p_Result_24_fu_636_p3 = esl_concat<1,7>(sin_basis_fu_630_p2.read(), p_Result_i_reg_1219.read());
}

void sin_or_cos_double_s::thread_p_Result_25_fu_889_p3() {
    p_Result_25_fu_889_p3 = p_Val2_25_fu_885_p1.read().range(63, 63);
}

void sin_or_cos_double_s::thread_p_Result_26_fu_911_p3() {
    p_Result_26_fu_911_p3 = esl_concat<1,3>(p_Result_19_reg_1097.read(), p_Val2_29_reg_1164.read());
}

void sin_or_cos_double_s::thread_p_Result_27_fu_1085_p4() {
    p_Result_27_fu_1085_p4 = esl_concat<12,52>(esl_concat<1,11>(p_Result_s_49_fu_1079_p3.read(), ret_V_6_reg_1435.read()), ret_V_7_reg_1440.read());
}

void sin_or_cos_double_s::thread_p_Result_i_i_fu_320_p4() {
    p_Result_i_i_fu_320_p4 = addr_V_fu_312_p3.read().range(10, 7);
}

void sin_or_cos_double_s::thread_p_Result_s_47_fu_1021_p3() {
    p_Result_s_47_fu_1021_p3 = (!tmp_9_fu_1016_p2.read()[0].is_01())? sc_lv<1>(): ((tmp_9_fu_1016_p2.read()[0].to_bool())? not_tmp_s_fu_1011_p2.read(): p_Result_25_fu_889_p3.read());
}

void sin_or_cos_double_s::thread_p_Result_s_48_fu_1029_p3() {
    p_Result_s_48_fu_1029_p3 = (!tmp_8_reg_1211.read()[0].is_01())? sc_lv<11>(): ((tmp_8_reg_1211.read()[0].to_bool())? ap_const_lv11_7FF: loc_V_2_fu_897_p4.read());
}

void sin_or_cos_double_s::thread_p_Result_s_49_fu_1079_p3() {
    p_Result_s_49_fu_1079_p3 = (!or_cond_reg_1425.read()[0].is_01())? sc_lv<1>(): ((or_cond_reg_1425.read()[0].to_bool())? p_Result_s_fu_1075_p2.read(): p_Result_s_47_reg_1430.read());
}

void sin_or_cos_double_s::thread_p_Result_s_fu_1075_p2() {
    p_Result_s_fu_1075_p2 = (p_Result_19_reg_1097.read() & not_do_cos_i_reg_1253.read());
}

void sin_or_cos_double_s::thread_p_Val2_11_fu_418_p3() {
    p_Val2_11_fu_418_p3 = (!tmp_14_fu_409_p1.read()[0].is_01())? sc_lv<124>(): ((tmp_14_fu_409_p1.read()[0].to_bool())? p_Val2_i_fu_413_p2.read(): p_Val2_8_reg_1153.read());
}

void sin_or_cos_double_s::thread_p_Val2_13_fu_487_p2() {
    p_Val2_13_fu_487_p2 = (!tmp_19_i_fu_484_p1.read().is_01())? sc_lv<124>(): p_Val2_11_reg_1170.read() << (unsigned short)tmp_19_i_fu_484_p1.read().to_uint();
}

void sin_or_cos_double_s::thread_p_Val2_14_fu_563_p3() {
    p_Val2_14_fu_563_p3 = (!isNeg_reg_1199.read()[0].is_01())? sc_lv<63>(): ((isNeg_reg_1199.read()[0].to_bool())? tmp_26_i_fu_553_p2.read(): tmp_27_i_fu_558_p2.read());
}

void sin_or_cos_double_s::thread_p_Val2_15_fu_580_p1() {
    p_Val2_15_fu_580_p1 = p_Val2_14_fu_563_p3.read().range(56-1, 0);
}

void sin_or_cos_double_s::thread_p_Val2_20_fu_737_p3() {
    p_Val2_20_fu_737_p3 = esl_concat<59,4>(p_Val2_19_reg_1343.read(), ap_const_lv4_0);
}

void sin_or_cos_double_s::thread_p_Val2_21_fu_785_p2() {
    p_Val2_21_fu_785_p2 = (!tmp_43_i_fu_778_p1.read().is_01() || !tmp_44_i_fu_782_p1.read().is_01())? sc_lv<64>(): (sc_bigint<64>(tmp_43_i_fu_778_p1.read()) + sc_bigint<64>(tmp_44_i_fu_782_p1.read()));
}

void sin_or_cos_double_s::thread_p_Val2_22_fu_794_p2() {
    p_Val2_22_fu_794_p2 = (!p_Val2_21_fu_785_p2.read().is_01() || !tmp_46_i_cast_fu_791_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(p_Val2_21_fu_785_p2.read()) + sc_bigint<64>(tmp_46_i_cast_fu_791_p1.read()));
}

void sin_or_cos_double_s::thread_p_Val2_23_fu_824_p2() {
    p_Val2_23_fu_824_p2 = (!p_Val2_22_reg_1383.read().is_01() || !tmp_48_i_cast_fu_821_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(p_Val2_22_reg_1383.read()) + sc_biguint<64>(tmp_48_i_cast_fu_821_p1.read()));
}

void sin_or_cos_double_s::thread_p_Val2_25_fu_885_p1() {
    p_Val2_25_fu_885_p1 = grp_scaled_fixed2ieee_fu_268_ap_return.read();
}

void sin_or_cos_double_s::thread_p_Val2_29_fu_403_p3() {
    p_Val2_29_fu_403_p3 = (!closepath_reg_1116.read()[0].is_01())? sc_lv<3>(): ((closepath_reg_1116.read()[0].to_bool())? ap_const_lv3_0: tmp_18_i_reg_1159.read());
}

void sin_or_cos_double_s::thread_p_Val2_4_fu_762_p0() {
    p_Val2_4_fu_762_p0 =  (sc_lv<35>) (p_Val2_4_fu_762_p00.read());
}

void sin_or_cos_double_s::thread_p_Val2_4_fu_762_p00() {
    p_Val2_4_fu_762_p00 = esl_zext<60,35>(tmp_40_i_reg_1338.read());
}

void sin_or_cos_double_s::thread_p_Val2_4_fu_762_p1() {
    p_Val2_4_fu_762_p1 =  (sc_lv<25>) (p_Val2_4_fu_762_p10.read());
}

void sin_or_cos_double_s::thread_p_Val2_4_fu_762_p10() {
    p_Val2_4_fu_762_p10 = esl_zext<60,25>(fourth_order_double_16_reg_1363.read());
}

void sin_or_cos_double_s::thread_p_Val2_4_fu_762_p2() {
    p_Val2_4_fu_762_p2 = (!p_Val2_4_fu_762_p0.read().is_01() || !p_Val2_4_fu_762_p1.read().is_01())? sc_lv<60>(): sc_biguint<35>(p_Val2_4_fu_762_p0.read()) * sc_biguint<25>(p_Val2_4_fu_762_p1.read());
}

void sin_or_cos_double_s::thread_p_Val2_i_fu_413_p2() {
    p_Val2_i_fu_413_p2 = (!ap_const_lv124_0.is_01() || !p_Val2_8_reg_1153.read().is_01())? sc_lv<124>(): (sc_biguint<124>(ap_const_lv124_0) - sc_biguint<124>(p_Val2_8_reg_1153.read()));
}

void sin_or_cos_double_s::thread_p_Val2_s_fu_274_p1() {
    p_Val2_s_fu_274_p1 = t_in.read();
}

void sin_or_cos_double_s::thread_p_cast_cast_fu_1004_p0() {
    p_cast_cast_fu_1004_p0 =  (sc_lv<1>) (do_cos.read());
}

void sin_or_cos_double_s::thread_p_cast_cast_fu_1004_p3() {
    p_cast_cast_fu_1004_p3 = (!p_cast_cast_fu_1004_p0.read()[0].is_01())? sc_lv<11>(): ((p_cast_cast_fu_1004_p0.read()[0].to_bool())? ap_const_lv11_3FF: ap_const_lv11_0);
}

void sin_or_cos_double_s::thread_r_V_3_fu_832_p2() {
    r_V_3_fu_832_p2 = (!p_Val2_23_fu_824_p2.read().is_01() || !tmp_50_i_cast_fu_829_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(p_Val2_23_fu_824_p2.read()) + sc_biguint<64>(tmp_50_i_cast_fu_829_p1.read()));
}

void sin_or_cos_double_s::thread_r_V_4_fu_342_p2() {
    r_V_4_fu_342_p2 = (!tmp_7_i_i_fu_339_p1.read().is_01())? sc_lv<256>(): ref_4oPi_table_256_V_q0.read() << (unsigned short)tmp_7_i_i_fu_339_p1.read().to_uint();
}

void sin_or_cos_double_s::thread_r_V_fu_878_p2() {
    r_V_fu_878_p2 = (!ap_const_lv12_0.is_01() || !rhs_V_fu_874_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_bigint<12>(rhs_V_fu_874_p1.read()));
}

void sin_or_cos_double_s::thread_ref_4oPi_table_256_V_address0() {
    ref_4oPi_table_256_V_address0 =  (sc_lv<4>) (tmp_5_i_i_fu_330_p1.read());
}

void sin_or_cos_double_s::thread_ref_4oPi_table_256_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ref_4oPi_table_256_V_ce0 = ap_const_logic_1;
    } else {
        ref_4oPi_table_256_V_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_ret_V_6_fu_1036_p3() {
    ret_V_6_fu_1036_p3 = (!or_cond_fu_1000_p2.read()[0].is_01())? sc_lv<11>(): ((or_cond_fu_1000_p2.read()[0].to_bool())? p_cast_cast_fu_1004_p3.read(): p_Result_s_48_fu_1029_p3.read());
}

void sin_or_cos_double_s::thread_ret_V_7_fu_1067_p3() {
    ret_V_7_fu_1067_p3 = (!tmp_10_fu_1062_p2.read()[0].is_01())? sc_lv<52>(): ((tmp_10_fu_1062_p2.read()[0].to_bool())? p_Result_1_cast_fu_1054_p3.read(): loc_V_3_fu_907_p1.read());
}

void sin_or_cos_double_s::thread_rhs_V_fu_874_p1() {
    rhs_V_fu_874_p1 = esl_sext<12,11>(p_Ex_V_ret_fu_857_p3.read());
}

void sin_or_cos_double_s::thread_sh_assign_2_cast_fu_545_p1() {
    sh_assign_2_cast_fu_545_p1 = esl_sext<32,12>(sh_assign_fu_538_p3.read());
}

void sin_or_cos_double_s::thread_sh_assign_fu_538_p3() {
    sh_assign_fu_538_p3 = (!isNeg_reg_1199.read()[0].is_01())? sc_lv<12>(): ((isNeg_reg_1199.read()[0].to_bool())? tmp_24_i_fu_532_p2.read(): sh_cast_fu_529_p1.read());
}

void sin_or_cos_double_s::thread_sh_cast_fu_529_p1() {
    sh_cast_fu_529_p1 = esl_sext<12,11>(Ex_V_reg_1193.read());
}

void sin_or_cos_double_s::thread_sin_basis_fu_630_p2() {
    sin_basis_fu_630_p2 = (tmp_fu_594_p10.read() ^ not_do_cos_i_fu_624_p2.read());
}

void sin_or_cos_double_s::thread_storemerge_i_fu_477_p3() {
    storemerge_i_fu_477_p3 = (!closepath_reg_1116.read()[0].is_01())? sc_lv<11>(): ((closepath_reg_1116.read()[0].to_bool())? tmp_i_fu_472_p2.read(): ap_const_lv11_0);
}

void sin_or_cos_double_s::thread_tmp_10_fu_1062_p2() {
    tmp_10_fu_1062_p2 = (or_cond_fu_1000_p2.read() | tmp_8_reg_1211.read());
}

void sin_or_cos_double_s::thread_tmp_13_fu_335_p1() {
    tmp_13_fu_335_p1 = addr_V_fu_312_p3.read().range(7-1, 0);
}

void sin_or_cos_double_s::thread_tmp_14_fu_409_p1() {
    tmp_14_fu_409_p1 = p_Val2_29_fu_403_p3.read().range(1-1, 0);
}

void sin_or_cos_double_s::thread_tmp_19_i_fu_484_p1() {
    tmp_19_i_fu_484_p1 = esl_zext<124,6>(Mx_zeros_V_reg_1180.read());
}

void sin_or_cos_double_s::thread_tmp_22_i_fu_502_p1() {
    tmp_22_i_fu_502_p1 = esl_zext<11,6>(Mx_zeros_V_reg_1180.read());
}

void sin_or_cos_double_s::thread_tmp_24_i_fu_532_p2() {
    tmp_24_i_fu_532_p2 = (!ap_const_lv12_0.is_01() || !sh_cast_fu_529_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_bigint<12>(sh_cast_fu_529_p1.read()));
}

void sin_or_cos_double_s::thread_tmp_25_i_fu_549_p1() {
    tmp_25_i_fu_549_p1 = esl_zext<63,32>(sh_assign_2_cast_fu_545_p1.read());
}

void sin_or_cos_double_s::thread_tmp_26_i_fu_553_p2() {
    tmp_26_i_fu_553_p2 = (!tmp_25_i_fu_549_p1.read().is_01())? sc_lv<63>(): Mx_V_reg_1186.read() >> (unsigned short)tmp_25_i_fu_549_p1.read().to_uint();
}

void sin_or_cos_double_s::thread_tmp_27_i_fu_558_p2() {
    tmp_27_i_fu_558_p2 = (!tmp_25_i_fu_549_p1.read().is_01())? sc_lv<63>(): Mx_V_reg_1186.read() << (unsigned short)tmp_25_i_fu_549_p1.read().to_uint();
}

void sin_or_cos_double_s::thread_tmp_41_i_fu_643_p1() {
    tmp_41_i_fu_643_p1 = esl_zext<64,8>(p_Result_24_fu_636_p3.read());
}

void sin_or_cos_double_s::thread_tmp_43_i_fu_778_p1() {
    tmp_43_i_fu_778_p1 = esl_sext<64,63>(p_Val2_20_fu_737_p3.read());
}

void sin_or_cos_double_s::thread_tmp_44_i_fu_782_p1() {
    tmp_44_i_fu_782_p1 = esl_sext<64,56>(tmp_6_i_reg_1348.read());
}

void sin_or_cos_double_s::thread_tmp_46_i_cast_fu_791_p1() {
    tmp_46_i_cast_fu_791_p1 = esl_sext<64,48>(tmp_8_i_reg_1353.read());
}

void sin_or_cos_double_s::thread_tmp_48_i_cast_fu_821_p1() {
    tmp_48_i_cast_fu_821_p1 = esl_zext<64,37>(tmp_1_reg_1388.read());
}

void sin_or_cos_double_s::thread_tmp_50_i_cast_fu_829_p1() {
    tmp_50_i_cast_fu_829_p1 = esl_zext<64,29>(tmp_2_reg_1378.read());
}

void sin_or_cos_double_s::thread_tmp_5_fu_993_p3() {
    tmp_5_fu_993_p3 = (!cos_basis_reg_1393.read()[0].is_01())? sc_lv<1>(): ((cos_basis_reg_1393.read()[0].to_bool())? tmp_3_fu_917_p18.read(): tmp_4_fu_955_p18.read());
}

void sin_or_cos_double_s::thread_tmp_5_i_i_fu_330_p1() {
    tmp_5_i_i_fu_330_p1 = esl_zext<64,4>(p_Result_i_i_fu_320_p4.read());
}

void sin_or_cos_double_s::thread_tmp_6_fu_519_p2() {
    tmp_6_fu_519_p2 = (!loc_V_reg_1103.read().is_01() || !ap_const_lv11_0.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_reg_1103.read() == ap_const_lv11_0);
}

void sin_or_cos_double_s::thread_tmp_7_fu_378_p2() {
    tmp_7_fu_378_p2 = (!loc_V_1_reg_1110.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_1_reg_1110.read() == ap_const_lv52_0);
}

void sin_or_cos_double_s::thread_tmp_7_i_i_fu_339_p1() {
    tmp_7_i_i_fu_339_p1 = esl_zext<256,7>(tmp_13_reg_1127.read());
}

void sin_or_cos_double_s::thread_tmp_8_fu_524_p2() {
    tmp_8_fu_524_p2 = (!loc_V_reg_1103.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_reg_1103.read() == ap_const_lv11_7FF);
}

void sin_or_cos_double_s::thread_tmp_9_fu_1016_p2() {
    tmp_9_fu_1016_p2 = (tmp_8_reg_1211.read() | tmp_5_fu_993_p3.read());
}

void sin_or_cos_double_s::thread_tmp_i3_i_fu_460_p3() {
    tmp_i3_i_fu_460_p3 = esl_cttz<64,64>(p_Result_23_fu_452_p3.read());
}

void sin_or_cos_double_s::thread_tmp_i_fu_472_p2() {
    tmp_i_fu_472_p2 = (!ap_const_lv11_403.is_01() || !loc_V_reg_1103.read().is_01())? sc_lv<11>(): (sc_bigint<11>(ap_const_lv11_403) + sc_biguint<11>(loc_V_reg_1103.read()));
}

void sin_or_cos_double_s::thread_tmp_s_fu_810_p2() {
    tmp_s_fu_810_p2 = (tmp_reg_1240.read() ^ ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            if ((esl_seteq<1,1,1>(grp_scaled_fixed2ieee_fu_268_ap_done.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()))) {
                ap_NS_fsm = ap_ST_fsm_state25;
            } else {
                ap_NS_fsm = ap_ST_fsm_state24;
            }
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXXXXXXXXXX";
            break;
    }
}

}

