// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module generic_asin_float_s (
        ap_clk,
        ap_rst,
        in_r,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [31:0] in_r;
output  [31:0] ap_return;

wire   [0:0] p_Result_s_fu_150_p3;
reg   [0:0] p_Result_s_reg_720;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
wire    ap_block_state29_pp0_stage0_iter28;
wire    ap_block_state30_pp0_stage0_iter29;
wire    ap_block_state31_pp0_stage0_iter30;
wire    ap_block_state32_pp0_stage0_iter31;
wire    ap_block_state33_pp0_stage0_iter32;
wire    ap_block_state34_pp0_stage0_iter33;
wire    ap_block_state35_pp0_stage0_iter34;
wire    ap_block_state36_pp0_stage0_iter35;
wire    ap_block_state37_pp0_stage0_iter36;
wire    ap_block_state38_pp0_stage0_iter37;
wire    ap_block_state39_pp0_stage0_iter38;
wire    ap_block_state40_pp0_stage0_iter39;
wire    ap_block_state41_pp0_stage0_iter40;
wire    ap_block_state42_pp0_stage0_iter41;
wire    ap_block_state43_pp0_stage0_iter42;
wire    ap_block_state44_pp0_stage0_iter43;
wire    ap_block_state45_pp0_stage0_iter44;
wire    ap_block_state46_pp0_stage0_iter45;
wire    ap_block_state47_pp0_stage0_iter46;
wire    ap_block_state48_pp0_stage0_iter47;
wire    ap_block_state49_pp0_stage0_iter48;
wire    ap_block_state50_pp0_stage0_iter49;
wire    ap_block_state51_pp0_stage0_iter50;
wire    ap_block_state52_pp0_stage0_iter51;
wire    ap_block_state53_pp0_stage0_iter52;
wire    ap_block_state54_pp0_stage0_iter53;
wire    ap_block_state55_pp0_stage0_iter54;
wire    ap_block_state56_pp0_stage0_iter55;
wire    ap_block_state57_pp0_stage0_iter56;
wire    ap_block_state58_pp0_stage0_iter57;
wire    ap_block_state59_pp0_stage0_iter58;
wire    ap_block_state60_pp0_stage0_iter59;
wire    ap_block_state61_pp0_stage0_iter60;
wire    ap_block_state62_pp0_stage0_iter61;
wire    ap_block_state63_pp0_stage0_iter62;
wire    ap_block_state64_pp0_stage0_iter63;
wire    ap_block_state65_pp0_stage0_iter64;
wire    ap_block_state66_pp0_stage0_iter65;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] p_Result_s_reg_720_pp0_iter1_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter2_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter3_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter4_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter5_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter6_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter7_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter8_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter9_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter10_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter11_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter12_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter13_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter14_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter15_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter16_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter17_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter18_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter19_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter20_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter21_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter22_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter23_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter24_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter25_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter26_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter27_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter28_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter29_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter30_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter31_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter32_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter33_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter34_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter35_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter36_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter37_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter38_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter39_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter40_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter41_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter42_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter43_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter44_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter45_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter46_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter47_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter48_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter49_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter50_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter51_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter52_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter53_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter54_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter55_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter56_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter57_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter58_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter59_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter60_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter61_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter62_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter63_reg;
reg   [0:0] p_Result_s_reg_720_pp0_iter64_reg;
wire   [31:0] out_1_fu_182_p3;
wire   [0:0] tmp_s_fu_191_p2;
reg   [0:0] tmp_s_reg_730;
reg   [0:0] tmp_s_reg_730_pp0_iter1_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter2_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter3_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter4_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter5_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter6_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter7_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter8_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter9_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter10_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter11_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter12_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter13_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter14_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter15_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter16_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter17_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter18_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter19_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter20_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter21_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter22_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter23_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter24_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter25_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter26_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter27_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter28_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter29_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter30_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter31_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter32_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter33_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter34_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter35_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter36_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter37_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter38_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter39_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter40_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter41_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter42_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter43_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter44_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter45_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter46_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter47_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter48_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter49_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter50_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter51_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter52_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter53_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter54_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter55_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter56_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter57_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter58_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter59_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter60_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter61_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter62_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter63_reg;
reg   [0:0] tmp_s_reg_730_pp0_iter64_reg;
wire   [0:0] tmp_1_fu_197_p2;
reg   [0:0] tmp_1_reg_734;
reg   [0:0] tmp_1_reg_734_pp0_iter1_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter2_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter3_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter4_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter5_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter6_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter7_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter8_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter9_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter10_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter11_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter12_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter13_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter14_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter15_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter16_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter17_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter18_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter19_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter20_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter21_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter22_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter23_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter24_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter25_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter26_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter27_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter28_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter29_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter30_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter31_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter32_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter33_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter34_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter35_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter36_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter37_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter38_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter39_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter40_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter41_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter42_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter43_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter44_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter45_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter46_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter47_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter48_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter49_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter50_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter51_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter52_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter53_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter54_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter55_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter56_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter57_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter58_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter59_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter60_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter61_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter62_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter63_reg;
reg   [0:0] tmp_1_reg_734_pp0_iter64_reg;
wire   [0:0] tmp_2_fu_203_p2;
reg   [0:0] tmp_2_reg_738;
reg   [0:0] tmp_2_reg_738_pp0_iter1_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter2_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter3_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter4_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter5_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter6_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter7_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter8_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter9_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter10_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter11_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter12_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter13_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter14_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter15_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter16_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter17_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter18_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter19_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter20_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter21_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter22_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter23_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter24_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter25_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter26_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter27_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter28_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter29_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter30_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter31_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter32_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter33_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter34_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter35_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter36_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter37_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter38_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter39_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter40_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter41_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter42_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter43_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter44_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter45_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter46_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter47_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter48_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter49_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter50_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter51_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter52_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter53_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter54_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter55_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter56_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter57_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter58_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter59_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter60_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter61_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter62_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter63_reg;
reg   [0:0] tmp_2_reg_738_pp0_iter64_reg;
wire   [0:0] tmp_3_fu_209_p2;
reg   [0:0] tmp_3_reg_742;
reg   [0:0] tmp_3_reg_742_pp0_iter1_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter2_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter3_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter4_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter5_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter6_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter7_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter8_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter9_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter10_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter11_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter12_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter13_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter14_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter15_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter16_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter17_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter18_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter19_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter20_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter21_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter22_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter23_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter24_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter25_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter26_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter27_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter28_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter29_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter30_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter31_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter32_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter33_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter34_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter35_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter36_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter37_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter38_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter39_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter40_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter41_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter42_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter43_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter44_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter45_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter46_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter47_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter48_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter49_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter50_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter51_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter52_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter53_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter54_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter55_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter56_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter57_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter58_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter59_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter60_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter61_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter62_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter63_reg;
reg   [0:0] tmp_3_reg_742_pp0_iter64_reg;
wire   [0:0] tmp_27_fu_215_p3;
reg   [0:0] tmp_27_reg_746;
reg   [0:0] tmp_27_reg_746_pp0_iter1_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter2_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter3_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter4_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter5_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter6_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter7_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter8_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter9_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter10_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter11_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter12_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter13_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter14_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter15_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter16_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter17_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter18_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter19_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter20_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter21_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter22_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter23_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter24_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter25_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter26_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter27_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter28_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter29_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter30_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter31_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter32_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter33_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter34_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter35_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter36_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter37_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter38_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter39_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter40_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter41_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter42_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter43_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter44_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter45_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter46_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter47_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter48_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter49_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter50_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter51_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter52_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter53_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter54_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter55_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter56_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter57_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter58_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter59_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter60_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter61_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter62_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter63_reg;
reg   [0:0] tmp_27_reg_746_pp0_iter64_reg;
wire   [62:0] tmp_29_fu_227_p1;
reg   [62:0] tmp_29_reg_750;
reg   [0:0] isneg_reg_755;
reg   [0:0] isneg_reg_755_pp0_iter1_reg;
reg   [10:0] exp_tmp_V_reg_761;
wire   [51:0] tmp_31_fu_249_p1;
reg   [51:0] tmp_31_reg_766;
wire   [0:0] tmp_4_fu_253_p2;
reg   [0:0] tmp_4_reg_771;
reg   [0:0] tmp_4_reg_771_pp0_iter1_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter2_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter3_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter4_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter5_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter6_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter7_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter8_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter9_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter10_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter11_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter12_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter13_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter14_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter15_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter16_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter17_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter18_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter19_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter20_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter21_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter22_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter23_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter24_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter25_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter26_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter27_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter28_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter29_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter30_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter31_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter32_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter33_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter34_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter35_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter36_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter37_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter38_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter39_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter40_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter41_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter42_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter43_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter44_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter45_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter46_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter47_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter48_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter49_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter50_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter51_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter52_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter53_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter54_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter55_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter56_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter57_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter58_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter59_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter60_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter61_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter62_reg;
reg   [0:0] tmp_4_reg_771_pp0_iter63_reg;
wire  signed [53:0] man_V_2_fu_285_p3;
reg  signed [53:0] man_V_2_reg_776;
wire   [0:0] tmp_7_fu_292_p2;
reg   [0:0] tmp_7_reg_783;
wire   [0:0] tmp_8_fu_303_p2;
reg   [0:0] tmp_8_reg_789;
wire  signed [11:0] sh_amt_fu_315_p3;
reg  signed [11:0] sh_amt_reg_795;
wire   [0:0] tmp_10_fu_323_p2;
reg   [0:0] tmp_10_reg_802;
wire   [54:0] t_V_fu_480_p3;
reg   [54:0] t_V_reg_808;
wire   [54:0] grp_doublecordic_apfixed_fu_135_ap_return;
reg   [54:0] z_V_reg_813;
wire   [0:0] tmp_19_fu_488_p2;
reg   [0:0] tmp_19_reg_819;
reg   [0:0] tmp_19_reg_819_pp0_iter57_reg;
reg   [0:0] tmp_19_reg_819_pp0_iter58_reg;
reg   [0:0] tmp_19_reg_819_pp0_iter59_reg;
reg   [0:0] tmp_19_reg_819_pp0_iter60_reg;
reg   [0:0] tmp_19_reg_819_pp0_iter61_reg;
reg   [0:0] tmp_19_reg_819_pp0_iter62_reg;
reg   [0:0] tmp_19_reg_819_pp0_iter63_reg;
reg   [0:0] tmp_19_reg_819_pp0_iter64_reg;
wire   [54:0] tmp_20_fu_494_p2;
reg   [54:0] tmp_20_reg_823;
wire   [0:0] is_neg_fu_500_p3;
reg   [0:0] is_neg_reg_828;
reg   [0:0] is_neg_reg_828_pp0_iter58_reg;
reg   [0:0] is_neg_reg_828_pp0_iter59_reg;
reg   [0:0] is_neg_reg_828_pp0_iter60_reg;
reg   [0:0] is_neg_reg_828_pp0_iter61_reg;
reg   [0:0] is_neg_reg_828_pp0_iter62_reg;
reg   [0:0] is_neg_reg_828_pp0_iter63_reg;
reg   [0:0] is_neg_reg_828_pp0_iter64_reg;
wire   [54:0] p_Val2_28_fu_507_p3;
reg   [54:0] p_Val2_28_reg_833;
wire   [31:0] msb_idx_fu_543_p2;
reg   [31:0] msb_idx_reg_839;
reg   [31:0] msb_idx_reg_839_pp0_iter58_reg;
reg   [31:0] msb_idx_reg_839_pp0_iter59_reg;
reg   [31:0] msb_idx_reg_839_pp0_iter60_reg;
reg   [31:0] msb_idx_reg_839_pp0_iter61_reg;
reg   [31:0] msb_idx_reg_839_pp0_iter62_reg;
reg   [31:0] msb_idx_reg_839_pp0_iter63_reg;
reg   [31:0] msb_idx_reg_839_pp0_iter64_reg;
wire   [30:0] tmp_34_fu_549_p1;
reg   [30:0] tmp_34_reg_844;
reg   [0:0] tmp_35_reg_849;
wire   [31:0] tmp32_V_3_fu_625_p3;
reg   [31:0] tmp32_V_3_reg_854;
wire   [31:0] tmp32_V_6_fu_633_p1;
reg   [31:0] tmp32_V_6_reg_859;
wire   [0:0] tmp_23_fu_647_p2;
reg   [0:0] tmp_23_reg_864;
wire   [31:0] p_s_fu_653_p3;
reg    grp_doublecordic_apfixed_fu_135_ap_ce;
reg    ap_predicate_op133_call_state4;
reg    ap_predicate_op186_call_state57;
reg   [31:0] ap_phi_mux_out_5_phi_fu_115_p14;
wire   [31:0] ap_phi_reg_pp0_iter0_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter1_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter2_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter3_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter4_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter5_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter6_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter7_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter8_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter9_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter10_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter11_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter12_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter13_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter14_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter15_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter16_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter17_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter18_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter19_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter20_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter21_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter22_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter23_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter24_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter25_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter26_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter27_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter28_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter29_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter30_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter31_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter32_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter33_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter34_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter35_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter36_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter37_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter38_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter39_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter40_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter41_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter42_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter43_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter44_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter45_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter46_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter47_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter48_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter49_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter50_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter51_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter52_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter53_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter54_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter55_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter56_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter57_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter58_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter59_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter60_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter61_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter62_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter63_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter64_out_5_reg_110;
reg   [31:0] ap_phi_reg_pp0_iter65_out_5_reg_110;
wire   [31:0] f_fu_694_p1;
wire    ap_block_pp0_stage0;
wire   [31:0] d_assign_fu_143_p0;
wire   [31:0] p_Val2_s_fu_146_p1;
wire   [31:0] inabs_neg_fu_172_p2;
wire   [31:0] inabs_fu_178_p1;
wire   [7:0] loc_V_fu_158_p4;
wire   [63:0] d_assign_fu_143_p1;
wire   [63:0] ireg_V_fu_223_p1;
wire   [22:0] loc_V_2_fu_168_p1;
wire   [11:0] tmp_6_fu_259_p1;
wire   [52:0] tmp_fu_268_p3;
wire   [53:0] p_Result_32_fu_275_p1;
wire   [53:0] man_V_1_fu_279_p2;
wire   [11:0] F2_fu_297_p2;
wire   [11:0] tmp_9_fu_309_p2;
wire   [11:0] exp_V_fu_262_p2;
wire  signed [31:0] sh_amt_cast_fu_329_p1;
wire   [53:0] tmp_14_fu_345_p1;
wire   [53:0] tmp_15_fu_349_p2;
wire  signed [54:0] tmp_11_fu_332_p1;
wire   [54:0] tmp_17_fu_365_p1;
wire   [0:0] sel_tmp2_fu_375_p2;
wire   [0:0] sel_tmp7_demorgan_fu_385_p2;
wire   [0:0] sel_tmp7_fu_389_p2;
wire   [0:0] tmp_12_fu_335_p2;
wire   [0:0] sel_tmp8_fu_395_p2;
wire   [0:0] sel_tmp9_fu_400_p2;
wire   [0:0] sel_tmp22_demorgan_fu_418_p2;
wire   [0:0] tmp_13_fu_340_p2;
wire   [0:0] sel_tmp4_fu_423_p2;
wire   [0:0] sel_tmp5_fu_429_p2;
wire   [54:0] tmp_18_fu_369_p2;
wire  signed [54:0] tmp_16_fu_354_p1;
wire   [0:0] sel_tmp1_fu_412_p2;
wire   [0:0] sel_tmp_fu_406_p2;
wire   [53:0] tmp_222_cast_fu_358_p3;
wire   [53:0] newSel1_fu_449_p3;
wire   [0:0] sel_tmp3_fu_380_p2;
wire   [0:0] or_cond_fu_443_p2;
wire   [54:0] newSel_fu_435_p3;
wire  signed [54:0] newSel28_cast_fu_456_p1;
wire   [0:0] or_cond1_fu_460_p2;
wire   [0:0] or_cond2_fu_474_p2;
wire   [54:0] newSel2_fu_466_p3;
reg   [54:0] p_Result_33_fu_513_p4;
wire   [63:0] p_Result_34_fu_523_p3;
reg   [63:0] tmp_21_fu_531_p3;
wire   [31:0] num_zeros_fu_539_p1;
wire   [30:0] msb_idx_1_fu_561_p3;
wire   [25:0] tmp_36_fu_571_p4;
wire   [31:0] msb_idx_3_cast_fu_567_p1;
wire   [31:0] tmp32_V_fu_587_p1;
wire   [31:0] tmp_22_fu_590_p2;
wire   [5:0] tmp_38_fu_602_p1;
wire   [5:0] tmp_39_fu_606_p2;
wire   [54:0] tmp_40_fu_612_p1;
wire   [54:0] tmp_41_fu_616_p2;
wire   [0:0] icmp_fu_581_p2;
wire   [31:0] tmp32_V_1_fu_596_p2;
wire   [31:0] tmp32_V_2_fu_621_p1;
wire   [31:0] grp_fu_140_p1;
wire   [7:0] p_Result_5_fu_637_p4;
wire   [7:0] tmp_43_fu_660_p1;
wire   [7:0] tmp27_cast_cast_fu_663_p3;
wire   [7:0] p_Repl2_46_trunc_fu_670_p2;
wire   [8:0] tmp_24_fu_676_p3;
wire   [31:0] p_Result_35_fu_683_p5;
wire   [31:0] out_to_int_fu_699_p1;
wire   [31:0] out_neg_fu_703_p2;
wire   [31:0] out_fu_709_p1;
reg   [31:0] in_r_int_reg;
reg    ap_condition_1514;
reg    ap_condition_773;

doublecordic_apfixed grp_doublecordic_apfixed_fu_135(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t_V_read(t_V_reg_808),
    .ap_return(grp_doublecordic_apfixed_fu_135_ap_return),
    .ap_ce(grp_doublecordic_apfixed_fu_135_ap_ce)
);

convert_uitofp_32lbW #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
convert_uitofp_32lbW_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp32_V_3_reg_854),
    .ce(1'b1),
    .dout(grp_fu_140_p1)
);

convert_fpext_32nocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
convert_fpext_32nocq_U43(
    .din0(d_assign_fu_143_p0),
    .dout(d_assign_fu_143_p1)
);

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_27_fu_215_p3 == 1'd1) & (tmp_3_fu_209_p2 == 1'd0) & (tmp_2_fu_203_p2 == 1'd0) & (tmp_1_fu_197_p2 == 1'd0) & (tmp_s_fu_191_p2 == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_191_p2 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_out_5_reg_110 <= 32'd2147483647;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_fu_203_p2 == 1'd1) & (tmp_1_fu_197_p2 == 1'd0) & (tmp_s_fu_191_p2 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_out_5_reg_110 <= out_1_fu_182_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_fu_197_p2 == 1'd1) & (tmp_s_fu_191_p2 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_out_5_reg_110 <= 32'd0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_phi_reg_pp0_iter1_out_5_reg_110 <= ap_phi_reg_pp0_iter0_out_5_reg_110;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1514)) begin
            ap_phi_reg_pp0_iter58_out_5_reg_110 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter58_out_5_reg_110 <= ap_phi_reg_pp0_iter57_out_5_reg_110;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_773)) begin
            ap_phi_reg_pp0_iter65_out_5_reg_110 <= p_s_fu_653_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter65_out_5_reg_110 <= ap_phi_reg_pp0_iter64_out_5_reg_110;
        end
    end
end

always @ (posedge ap_clk) begin
    in_r_int_reg <= in_r;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_phi_reg_pp0_iter10_out_5_reg_110 <= ap_phi_reg_pp0_iter9_out_5_reg_110;
        ap_phi_reg_pp0_iter11_out_5_reg_110 <= ap_phi_reg_pp0_iter10_out_5_reg_110;
        ap_phi_reg_pp0_iter12_out_5_reg_110 <= ap_phi_reg_pp0_iter11_out_5_reg_110;
        ap_phi_reg_pp0_iter13_out_5_reg_110 <= ap_phi_reg_pp0_iter12_out_5_reg_110;
        ap_phi_reg_pp0_iter14_out_5_reg_110 <= ap_phi_reg_pp0_iter13_out_5_reg_110;
        ap_phi_reg_pp0_iter15_out_5_reg_110 <= ap_phi_reg_pp0_iter14_out_5_reg_110;
        ap_phi_reg_pp0_iter16_out_5_reg_110 <= ap_phi_reg_pp0_iter15_out_5_reg_110;
        ap_phi_reg_pp0_iter17_out_5_reg_110 <= ap_phi_reg_pp0_iter16_out_5_reg_110;
        ap_phi_reg_pp0_iter18_out_5_reg_110 <= ap_phi_reg_pp0_iter17_out_5_reg_110;
        ap_phi_reg_pp0_iter19_out_5_reg_110 <= ap_phi_reg_pp0_iter18_out_5_reg_110;
        ap_phi_reg_pp0_iter20_out_5_reg_110 <= ap_phi_reg_pp0_iter19_out_5_reg_110;
        ap_phi_reg_pp0_iter21_out_5_reg_110 <= ap_phi_reg_pp0_iter20_out_5_reg_110;
        ap_phi_reg_pp0_iter22_out_5_reg_110 <= ap_phi_reg_pp0_iter21_out_5_reg_110;
        ap_phi_reg_pp0_iter23_out_5_reg_110 <= ap_phi_reg_pp0_iter22_out_5_reg_110;
        ap_phi_reg_pp0_iter24_out_5_reg_110 <= ap_phi_reg_pp0_iter23_out_5_reg_110;
        ap_phi_reg_pp0_iter25_out_5_reg_110 <= ap_phi_reg_pp0_iter24_out_5_reg_110;
        ap_phi_reg_pp0_iter26_out_5_reg_110 <= ap_phi_reg_pp0_iter25_out_5_reg_110;
        ap_phi_reg_pp0_iter27_out_5_reg_110 <= ap_phi_reg_pp0_iter26_out_5_reg_110;
        ap_phi_reg_pp0_iter28_out_5_reg_110 <= ap_phi_reg_pp0_iter27_out_5_reg_110;
        ap_phi_reg_pp0_iter29_out_5_reg_110 <= ap_phi_reg_pp0_iter28_out_5_reg_110;
        ap_phi_reg_pp0_iter2_out_5_reg_110 <= ap_phi_reg_pp0_iter1_out_5_reg_110;
        ap_phi_reg_pp0_iter30_out_5_reg_110 <= ap_phi_reg_pp0_iter29_out_5_reg_110;
        ap_phi_reg_pp0_iter31_out_5_reg_110 <= ap_phi_reg_pp0_iter30_out_5_reg_110;
        ap_phi_reg_pp0_iter32_out_5_reg_110 <= ap_phi_reg_pp0_iter31_out_5_reg_110;
        ap_phi_reg_pp0_iter33_out_5_reg_110 <= ap_phi_reg_pp0_iter32_out_5_reg_110;
        ap_phi_reg_pp0_iter34_out_5_reg_110 <= ap_phi_reg_pp0_iter33_out_5_reg_110;
        ap_phi_reg_pp0_iter35_out_5_reg_110 <= ap_phi_reg_pp0_iter34_out_5_reg_110;
        ap_phi_reg_pp0_iter36_out_5_reg_110 <= ap_phi_reg_pp0_iter35_out_5_reg_110;
        ap_phi_reg_pp0_iter37_out_5_reg_110 <= ap_phi_reg_pp0_iter36_out_5_reg_110;
        ap_phi_reg_pp0_iter38_out_5_reg_110 <= ap_phi_reg_pp0_iter37_out_5_reg_110;
        ap_phi_reg_pp0_iter39_out_5_reg_110 <= ap_phi_reg_pp0_iter38_out_5_reg_110;
        ap_phi_reg_pp0_iter3_out_5_reg_110 <= ap_phi_reg_pp0_iter2_out_5_reg_110;
        ap_phi_reg_pp0_iter40_out_5_reg_110 <= ap_phi_reg_pp0_iter39_out_5_reg_110;
        ap_phi_reg_pp0_iter41_out_5_reg_110 <= ap_phi_reg_pp0_iter40_out_5_reg_110;
        ap_phi_reg_pp0_iter42_out_5_reg_110 <= ap_phi_reg_pp0_iter41_out_5_reg_110;
        ap_phi_reg_pp0_iter43_out_5_reg_110 <= ap_phi_reg_pp0_iter42_out_5_reg_110;
        ap_phi_reg_pp0_iter44_out_5_reg_110 <= ap_phi_reg_pp0_iter43_out_5_reg_110;
        ap_phi_reg_pp0_iter45_out_5_reg_110 <= ap_phi_reg_pp0_iter44_out_5_reg_110;
        ap_phi_reg_pp0_iter46_out_5_reg_110 <= ap_phi_reg_pp0_iter45_out_5_reg_110;
        ap_phi_reg_pp0_iter47_out_5_reg_110 <= ap_phi_reg_pp0_iter46_out_5_reg_110;
        ap_phi_reg_pp0_iter48_out_5_reg_110 <= ap_phi_reg_pp0_iter47_out_5_reg_110;
        ap_phi_reg_pp0_iter49_out_5_reg_110 <= ap_phi_reg_pp0_iter48_out_5_reg_110;
        ap_phi_reg_pp0_iter4_out_5_reg_110 <= ap_phi_reg_pp0_iter3_out_5_reg_110;
        ap_phi_reg_pp0_iter50_out_5_reg_110 <= ap_phi_reg_pp0_iter49_out_5_reg_110;
        ap_phi_reg_pp0_iter51_out_5_reg_110 <= ap_phi_reg_pp0_iter50_out_5_reg_110;
        ap_phi_reg_pp0_iter52_out_5_reg_110 <= ap_phi_reg_pp0_iter51_out_5_reg_110;
        ap_phi_reg_pp0_iter53_out_5_reg_110 <= ap_phi_reg_pp0_iter52_out_5_reg_110;
        ap_phi_reg_pp0_iter54_out_5_reg_110 <= ap_phi_reg_pp0_iter53_out_5_reg_110;
        ap_phi_reg_pp0_iter55_out_5_reg_110 <= ap_phi_reg_pp0_iter54_out_5_reg_110;
        ap_phi_reg_pp0_iter56_out_5_reg_110 <= ap_phi_reg_pp0_iter55_out_5_reg_110;
        ap_phi_reg_pp0_iter57_out_5_reg_110 <= ap_phi_reg_pp0_iter56_out_5_reg_110;
        ap_phi_reg_pp0_iter59_out_5_reg_110 <= ap_phi_reg_pp0_iter58_out_5_reg_110;
        ap_phi_reg_pp0_iter5_out_5_reg_110 <= ap_phi_reg_pp0_iter4_out_5_reg_110;
        ap_phi_reg_pp0_iter60_out_5_reg_110 <= ap_phi_reg_pp0_iter59_out_5_reg_110;
        ap_phi_reg_pp0_iter61_out_5_reg_110 <= ap_phi_reg_pp0_iter60_out_5_reg_110;
        ap_phi_reg_pp0_iter62_out_5_reg_110 <= ap_phi_reg_pp0_iter61_out_5_reg_110;
        ap_phi_reg_pp0_iter63_out_5_reg_110 <= ap_phi_reg_pp0_iter62_out_5_reg_110;
        ap_phi_reg_pp0_iter64_out_5_reg_110 <= ap_phi_reg_pp0_iter63_out_5_reg_110;
        ap_phi_reg_pp0_iter6_out_5_reg_110 <= ap_phi_reg_pp0_iter5_out_5_reg_110;
        ap_phi_reg_pp0_iter7_out_5_reg_110 <= ap_phi_reg_pp0_iter6_out_5_reg_110;
        ap_phi_reg_pp0_iter8_out_5_reg_110 <= ap_phi_reg_pp0_iter7_out_5_reg_110;
        ap_phi_reg_pp0_iter9_out_5_reg_110 <= ap_phi_reg_pp0_iter8_out_5_reg_110;
        is_neg_reg_828_pp0_iter58_reg <= is_neg_reg_828;
        is_neg_reg_828_pp0_iter59_reg <= is_neg_reg_828_pp0_iter58_reg;
        is_neg_reg_828_pp0_iter60_reg <= is_neg_reg_828_pp0_iter59_reg;
        is_neg_reg_828_pp0_iter61_reg <= is_neg_reg_828_pp0_iter60_reg;
        is_neg_reg_828_pp0_iter62_reg <= is_neg_reg_828_pp0_iter61_reg;
        is_neg_reg_828_pp0_iter63_reg <= is_neg_reg_828_pp0_iter62_reg;
        is_neg_reg_828_pp0_iter64_reg <= is_neg_reg_828_pp0_iter63_reg;
        isneg_reg_755_pp0_iter1_reg <= isneg_reg_755;
        msb_idx_reg_839_pp0_iter58_reg <= msb_idx_reg_839;
        msb_idx_reg_839_pp0_iter59_reg <= msb_idx_reg_839_pp0_iter58_reg;
        msb_idx_reg_839_pp0_iter60_reg <= msb_idx_reg_839_pp0_iter59_reg;
        msb_idx_reg_839_pp0_iter61_reg <= msb_idx_reg_839_pp0_iter60_reg;
        msb_idx_reg_839_pp0_iter62_reg <= msb_idx_reg_839_pp0_iter61_reg;
        msb_idx_reg_839_pp0_iter63_reg <= msb_idx_reg_839_pp0_iter62_reg;
        msb_idx_reg_839_pp0_iter64_reg <= msb_idx_reg_839_pp0_iter63_reg;
        p_Result_s_reg_720 <= p_Val2_s_fu_146_p1[32'd31];
        p_Result_s_reg_720_pp0_iter10_reg <= p_Result_s_reg_720_pp0_iter9_reg;
        p_Result_s_reg_720_pp0_iter11_reg <= p_Result_s_reg_720_pp0_iter10_reg;
        p_Result_s_reg_720_pp0_iter12_reg <= p_Result_s_reg_720_pp0_iter11_reg;
        p_Result_s_reg_720_pp0_iter13_reg <= p_Result_s_reg_720_pp0_iter12_reg;
        p_Result_s_reg_720_pp0_iter14_reg <= p_Result_s_reg_720_pp0_iter13_reg;
        p_Result_s_reg_720_pp0_iter15_reg <= p_Result_s_reg_720_pp0_iter14_reg;
        p_Result_s_reg_720_pp0_iter16_reg <= p_Result_s_reg_720_pp0_iter15_reg;
        p_Result_s_reg_720_pp0_iter17_reg <= p_Result_s_reg_720_pp0_iter16_reg;
        p_Result_s_reg_720_pp0_iter18_reg <= p_Result_s_reg_720_pp0_iter17_reg;
        p_Result_s_reg_720_pp0_iter19_reg <= p_Result_s_reg_720_pp0_iter18_reg;
        p_Result_s_reg_720_pp0_iter1_reg <= p_Result_s_reg_720;
        p_Result_s_reg_720_pp0_iter20_reg <= p_Result_s_reg_720_pp0_iter19_reg;
        p_Result_s_reg_720_pp0_iter21_reg <= p_Result_s_reg_720_pp0_iter20_reg;
        p_Result_s_reg_720_pp0_iter22_reg <= p_Result_s_reg_720_pp0_iter21_reg;
        p_Result_s_reg_720_pp0_iter23_reg <= p_Result_s_reg_720_pp0_iter22_reg;
        p_Result_s_reg_720_pp0_iter24_reg <= p_Result_s_reg_720_pp0_iter23_reg;
        p_Result_s_reg_720_pp0_iter25_reg <= p_Result_s_reg_720_pp0_iter24_reg;
        p_Result_s_reg_720_pp0_iter26_reg <= p_Result_s_reg_720_pp0_iter25_reg;
        p_Result_s_reg_720_pp0_iter27_reg <= p_Result_s_reg_720_pp0_iter26_reg;
        p_Result_s_reg_720_pp0_iter28_reg <= p_Result_s_reg_720_pp0_iter27_reg;
        p_Result_s_reg_720_pp0_iter29_reg <= p_Result_s_reg_720_pp0_iter28_reg;
        p_Result_s_reg_720_pp0_iter2_reg <= p_Result_s_reg_720_pp0_iter1_reg;
        p_Result_s_reg_720_pp0_iter30_reg <= p_Result_s_reg_720_pp0_iter29_reg;
        p_Result_s_reg_720_pp0_iter31_reg <= p_Result_s_reg_720_pp0_iter30_reg;
        p_Result_s_reg_720_pp0_iter32_reg <= p_Result_s_reg_720_pp0_iter31_reg;
        p_Result_s_reg_720_pp0_iter33_reg <= p_Result_s_reg_720_pp0_iter32_reg;
        p_Result_s_reg_720_pp0_iter34_reg <= p_Result_s_reg_720_pp0_iter33_reg;
        p_Result_s_reg_720_pp0_iter35_reg <= p_Result_s_reg_720_pp0_iter34_reg;
        p_Result_s_reg_720_pp0_iter36_reg <= p_Result_s_reg_720_pp0_iter35_reg;
        p_Result_s_reg_720_pp0_iter37_reg <= p_Result_s_reg_720_pp0_iter36_reg;
        p_Result_s_reg_720_pp0_iter38_reg <= p_Result_s_reg_720_pp0_iter37_reg;
        p_Result_s_reg_720_pp0_iter39_reg <= p_Result_s_reg_720_pp0_iter38_reg;
        p_Result_s_reg_720_pp0_iter3_reg <= p_Result_s_reg_720_pp0_iter2_reg;
        p_Result_s_reg_720_pp0_iter40_reg <= p_Result_s_reg_720_pp0_iter39_reg;
        p_Result_s_reg_720_pp0_iter41_reg <= p_Result_s_reg_720_pp0_iter40_reg;
        p_Result_s_reg_720_pp0_iter42_reg <= p_Result_s_reg_720_pp0_iter41_reg;
        p_Result_s_reg_720_pp0_iter43_reg <= p_Result_s_reg_720_pp0_iter42_reg;
        p_Result_s_reg_720_pp0_iter44_reg <= p_Result_s_reg_720_pp0_iter43_reg;
        p_Result_s_reg_720_pp0_iter45_reg <= p_Result_s_reg_720_pp0_iter44_reg;
        p_Result_s_reg_720_pp0_iter46_reg <= p_Result_s_reg_720_pp0_iter45_reg;
        p_Result_s_reg_720_pp0_iter47_reg <= p_Result_s_reg_720_pp0_iter46_reg;
        p_Result_s_reg_720_pp0_iter48_reg <= p_Result_s_reg_720_pp0_iter47_reg;
        p_Result_s_reg_720_pp0_iter49_reg <= p_Result_s_reg_720_pp0_iter48_reg;
        p_Result_s_reg_720_pp0_iter4_reg <= p_Result_s_reg_720_pp0_iter3_reg;
        p_Result_s_reg_720_pp0_iter50_reg <= p_Result_s_reg_720_pp0_iter49_reg;
        p_Result_s_reg_720_pp0_iter51_reg <= p_Result_s_reg_720_pp0_iter50_reg;
        p_Result_s_reg_720_pp0_iter52_reg <= p_Result_s_reg_720_pp0_iter51_reg;
        p_Result_s_reg_720_pp0_iter53_reg <= p_Result_s_reg_720_pp0_iter52_reg;
        p_Result_s_reg_720_pp0_iter54_reg <= p_Result_s_reg_720_pp0_iter53_reg;
        p_Result_s_reg_720_pp0_iter55_reg <= p_Result_s_reg_720_pp0_iter54_reg;
        p_Result_s_reg_720_pp0_iter56_reg <= p_Result_s_reg_720_pp0_iter55_reg;
        p_Result_s_reg_720_pp0_iter57_reg <= p_Result_s_reg_720_pp0_iter56_reg;
        p_Result_s_reg_720_pp0_iter58_reg <= p_Result_s_reg_720_pp0_iter57_reg;
        p_Result_s_reg_720_pp0_iter59_reg <= p_Result_s_reg_720_pp0_iter58_reg;
        p_Result_s_reg_720_pp0_iter5_reg <= p_Result_s_reg_720_pp0_iter4_reg;
        p_Result_s_reg_720_pp0_iter60_reg <= p_Result_s_reg_720_pp0_iter59_reg;
        p_Result_s_reg_720_pp0_iter61_reg <= p_Result_s_reg_720_pp0_iter60_reg;
        p_Result_s_reg_720_pp0_iter62_reg <= p_Result_s_reg_720_pp0_iter61_reg;
        p_Result_s_reg_720_pp0_iter63_reg <= p_Result_s_reg_720_pp0_iter62_reg;
        p_Result_s_reg_720_pp0_iter64_reg <= p_Result_s_reg_720_pp0_iter63_reg;
        p_Result_s_reg_720_pp0_iter6_reg <= p_Result_s_reg_720_pp0_iter5_reg;
        p_Result_s_reg_720_pp0_iter7_reg <= p_Result_s_reg_720_pp0_iter6_reg;
        p_Result_s_reg_720_pp0_iter8_reg <= p_Result_s_reg_720_pp0_iter7_reg;
        p_Result_s_reg_720_pp0_iter9_reg <= p_Result_s_reg_720_pp0_iter8_reg;
        tmp_19_reg_819_pp0_iter57_reg <= tmp_19_reg_819;
        tmp_19_reg_819_pp0_iter58_reg <= tmp_19_reg_819_pp0_iter57_reg;
        tmp_19_reg_819_pp0_iter59_reg <= tmp_19_reg_819_pp0_iter58_reg;
        tmp_19_reg_819_pp0_iter60_reg <= tmp_19_reg_819_pp0_iter59_reg;
        tmp_19_reg_819_pp0_iter61_reg <= tmp_19_reg_819_pp0_iter60_reg;
        tmp_19_reg_819_pp0_iter62_reg <= tmp_19_reg_819_pp0_iter61_reg;
        tmp_19_reg_819_pp0_iter63_reg <= tmp_19_reg_819_pp0_iter62_reg;
        tmp_19_reg_819_pp0_iter64_reg <= tmp_19_reg_819_pp0_iter63_reg;
        tmp_1_reg_734_pp0_iter10_reg <= tmp_1_reg_734_pp0_iter9_reg;
        tmp_1_reg_734_pp0_iter11_reg <= tmp_1_reg_734_pp0_iter10_reg;
        tmp_1_reg_734_pp0_iter12_reg <= tmp_1_reg_734_pp0_iter11_reg;
        tmp_1_reg_734_pp0_iter13_reg <= tmp_1_reg_734_pp0_iter12_reg;
        tmp_1_reg_734_pp0_iter14_reg <= tmp_1_reg_734_pp0_iter13_reg;
        tmp_1_reg_734_pp0_iter15_reg <= tmp_1_reg_734_pp0_iter14_reg;
        tmp_1_reg_734_pp0_iter16_reg <= tmp_1_reg_734_pp0_iter15_reg;
        tmp_1_reg_734_pp0_iter17_reg <= tmp_1_reg_734_pp0_iter16_reg;
        tmp_1_reg_734_pp0_iter18_reg <= tmp_1_reg_734_pp0_iter17_reg;
        tmp_1_reg_734_pp0_iter19_reg <= tmp_1_reg_734_pp0_iter18_reg;
        tmp_1_reg_734_pp0_iter1_reg <= tmp_1_reg_734;
        tmp_1_reg_734_pp0_iter20_reg <= tmp_1_reg_734_pp0_iter19_reg;
        tmp_1_reg_734_pp0_iter21_reg <= tmp_1_reg_734_pp0_iter20_reg;
        tmp_1_reg_734_pp0_iter22_reg <= tmp_1_reg_734_pp0_iter21_reg;
        tmp_1_reg_734_pp0_iter23_reg <= tmp_1_reg_734_pp0_iter22_reg;
        tmp_1_reg_734_pp0_iter24_reg <= tmp_1_reg_734_pp0_iter23_reg;
        tmp_1_reg_734_pp0_iter25_reg <= tmp_1_reg_734_pp0_iter24_reg;
        tmp_1_reg_734_pp0_iter26_reg <= tmp_1_reg_734_pp0_iter25_reg;
        tmp_1_reg_734_pp0_iter27_reg <= tmp_1_reg_734_pp0_iter26_reg;
        tmp_1_reg_734_pp0_iter28_reg <= tmp_1_reg_734_pp0_iter27_reg;
        tmp_1_reg_734_pp0_iter29_reg <= tmp_1_reg_734_pp0_iter28_reg;
        tmp_1_reg_734_pp0_iter2_reg <= tmp_1_reg_734_pp0_iter1_reg;
        tmp_1_reg_734_pp0_iter30_reg <= tmp_1_reg_734_pp0_iter29_reg;
        tmp_1_reg_734_pp0_iter31_reg <= tmp_1_reg_734_pp0_iter30_reg;
        tmp_1_reg_734_pp0_iter32_reg <= tmp_1_reg_734_pp0_iter31_reg;
        tmp_1_reg_734_pp0_iter33_reg <= tmp_1_reg_734_pp0_iter32_reg;
        tmp_1_reg_734_pp0_iter34_reg <= tmp_1_reg_734_pp0_iter33_reg;
        tmp_1_reg_734_pp0_iter35_reg <= tmp_1_reg_734_pp0_iter34_reg;
        tmp_1_reg_734_pp0_iter36_reg <= tmp_1_reg_734_pp0_iter35_reg;
        tmp_1_reg_734_pp0_iter37_reg <= tmp_1_reg_734_pp0_iter36_reg;
        tmp_1_reg_734_pp0_iter38_reg <= tmp_1_reg_734_pp0_iter37_reg;
        tmp_1_reg_734_pp0_iter39_reg <= tmp_1_reg_734_pp0_iter38_reg;
        tmp_1_reg_734_pp0_iter3_reg <= tmp_1_reg_734_pp0_iter2_reg;
        tmp_1_reg_734_pp0_iter40_reg <= tmp_1_reg_734_pp0_iter39_reg;
        tmp_1_reg_734_pp0_iter41_reg <= tmp_1_reg_734_pp0_iter40_reg;
        tmp_1_reg_734_pp0_iter42_reg <= tmp_1_reg_734_pp0_iter41_reg;
        tmp_1_reg_734_pp0_iter43_reg <= tmp_1_reg_734_pp0_iter42_reg;
        tmp_1_reg_734_pp0_iter44_reg <= tmp_1_reg_734_pp0_iter43_reg;
        tmp_1_reg_734_pp0_iter45_reg <= tmp_1_reg_734_pp0_iter44_reg;
        tmp_1_reg_734_pp0_iter46_reg <= tmp_1_reg_734_pp0_iter45_reg;
        tmp_1_reg_734_pp0_iter47_reg <= tmp_1_reg_734_pp0_iter46_reg;
        tmp_1_reg_734_pp0_iter48_reg <= tmp_1_reg_734_pp0_iter47_reg;
        tmp_1_reg_734_pp0_iter49_reg <= tmp_1_reg_734_pp0_iter48_reg;
        tmp_1_reg_734_pp0_iter4_reg <= tmp_1_reg_734_pp0_iter3_reg;
        tmp_1_reg_734_pp0_iter50_reg <= tmp_1_reg_734_pp0_iter49_reg;
        tmp_1_reg_734_pp0_iter51_reg <= tmp_1_reg_734_pp0_iter50_reg;
        tmp_1_reg_734_pp0_iter52_reg <= tmp_1_reg_734_pp0_iter51_reg;
        tmp_1_reg_734_pp0_iter53_reg <= tmp_1_reg_734_pp0_iter52_reg;
        tmp_1_reg_734_pp0_iter54_reg <= tmp_1_reg_734_pp0_iter53_reg;
        tmp_1_reg_734_pp0_iter55_reg <= tmp_1_reg_734_pp0_iter54_reg;
        tmp_1_reg_734_pp0_iter56_reg <= tmp_1_reg_734_pp0_iter55_reg;
        tmp_1_reg_734_pp0_iter57_reg <= tmp_1_reg_734_pp0_iter56_reg;
        tmp_1_reg_734_pp0_iter58_reg <= tmp_1_reg_734_pp0_iter57_reg;
        tmp_1_reg_734_pp0_iter59_reg <= tmp_1_reg_734_pp0_iter58_reg;
        tmp_1_reg_734_pp0_iter5_reg <= tmp_1_reg_734_pp0_iter4_reg;
        tmp_1_reg_734_pp0_iter60_reg <= tmp_1_reg_734_pp0_iter59_reg;
        tmp_1_reg_734_pp0_iter61_reg <= tmp_1_reg_734_pp0_iter60_reg;
        tmp_1_reg_734_pp0_iter62_reg <= tmp_1_reg_734_pp0_iter61_reg;
        tmp_1_reg_734_pp0_iter63_reg <= tmp_1_reg_734_pp0_iter62_reg;
        tmp_1_reg_734_pp0_iter64_reg <= tmp_1_reg_734_pp0_iter63_reg;
        tmp_1_reg_734_pp0_iter6_reg <= tmp_1_reg_734_pp0_iter5_reg;
        tmp_1_reg_734_pp0_iter7_reg <= tmp_1_reg_734_pp0_iter6_reg;
        tmp_1_reg_734_pp0_iter8_reg <= tmp_1_reg_734_pp0_iter7_reg;
        tmp_1_reg_734_pp0_iter9_reg <= tmp_1_reg_734_pp0_iter8_reg;
        tmp_27_reg_746_pp0_iter10_reg <= tmp_27_reg_746_pp0_iter9_reg;
        tmp_27_reg_746_pp0_iter11_reg <= tmp_27_reg_746_pp0_iter10_reg;
        tmp_27_reg_746_pp0_iter12_reg <= tmp_27_reg_746_pp0_iter11_reg;
        tmp_27_reg_746_pp0_iter13_reg <= tmp_27_reg_746_pp0_iter12_reg;
        tmp_27_reg_746_pp0_iter14_reg <= tmp_27_reg_746_pp0_iter13_reg;
        tmp_27_reg_746_pp0_iter15_reg <= tmp_27_reg_746_pp0_iter14_reg;
        tmp_27_reg_746_pp0_iter16_reg <= tmp_27_reg_746_pp0_iter15_reg;
        tmp_27_reg_746_pp0_iter17_reg <= tmp_27_reg_746_pp0_iter16_reg;
        tmp_27_reg_746_pp0_iter18_reg <= tmp_27_reg_746_pp0_iter17_reg;
        tmp_27_reg_746_pp0_iter19_reg <= tmp_27_reg_746_pp0_iter18_reg;
        tmp_27_reg_746_pp0_iter1_reg <= tmp_27_reg_746;
        tmp_27_reg_746_pp0_iter20_reg <= tmp_27_reg_746_pp0_iter19_reg;
        tmp_27_reg_746_pp0_iter21_reg <= tmp_27_reg_746_pp0_iter20_reg;
        tmp_27_reg_746_pp0_iter22_reg <= tmp_27_reg_746_pp0_iter21_reg;
        tmp_27_reg_746_pp0_iter23_reg <= tmp_27_reg_746_pp0_iter22_reg;
        tmp_27_reg_746_pp0_iter24_reg <= tmp_27_reg_746_pp0_iter23_reg;
        tmp_27_reg_746_pp0_iter25_reg <= tmp_27_reg_746_pp0_iter24_reg;
        tmp_27_reg_746_pp0_iter26_reg <= tmp_27_reg_746_pp0_iter25_reg;
        tmp_27_reg_746_pp0_iter27_reg <= tmp_27_reg_746_pp0_iter26_reg;
        tmp_27_reg_746_pp0_iter28_reg <= tmp_27_reg_746_pp0_iter27_reg;
        tmp_27_reg_746_pp0_iter29_reg <= tmp_27_reg_746_pp0_iter28_reg;
        tmp_27_reg_746_pp0_iter2_reg <= tmp_27_reg_746_pp0_iter1_reg;
        tmp_27_reg_746_pp0_iter30_reg <= tmp_27_reg_746_pp0_iter29_reg;
        tmp_27_reg_746_pp0_iter31_reg <= tmp_27_reg_746_pp0_iter30_reg;
        tmp_27_reg_746_pp0_iter32_reg <= tmp_27_reg_746_pp0_iter31_reg;
        tmp_27_reg_746_pp0_iter33_reg <= tmp_27_reg_746_pp0_iter32_reg;
        tmp_27_reg_746_pp0_iter34_reg <= tmp_27_reg_746_pp0_iter33_reg;
        tmp_27_reg_746_pp0_iter35_reg <= tmp_27_reg_746_pp0_iter34_reg;
        tmp_27_reg_746_pp0_iter36_reg <= tmp_27_reg_746_pp0_iter35_reg;
        tmp_27_reg_746_pp0_iter37_reg <= tmp_27_reg_746_pp0_iter36_reg;
        tmp_27_reg_746_pp0_iter38_reg <= tmp_27_reg_746_pp0_iter37_reg;
        tmp_27_reg_746_pp0_iter39_reg <= tmp_27_reg_746_pp0_iter38_reg;
        tmp_27_reg_746_pp0_iter3_reg <= tmp_27_reg_746_pp0_iter2_reg;
        tmp_27_reg_746_pp0_iter40_reg <= tmp_27_reg_746_pp0_iter39_reg;
        tmp_27_reg_746_pp0_iter41_reg <= tmp_27_reg_746_pp0_iter40_reg;
        tmp_27_reg_746_pp0_iter42_reg <= tmp_27_reg_746_pp0_iter41_reg;
        tmp_27_reg_746_pp0_iter43_reg <= tmp_27_reg_746_pp0_iter42_reg;
        tmp_27_reg_746_pp0_iter44_reg <= tmp_27_reg_746_pp0_iter43_reg;
        tmp_27_reg_746_pp0_iter45_reg <= tmp_27_reg_746_pp0_iter44_reg;
        tmp_27_reg_746_pp0_iter46_reg <= tmp_27_reg_746_pp0_iter45_reg;
        tmp_27_reg_746_pp0_iter47_reg <= tmp_27_reg_746_pp0_iter46_reg;
        tmp_27_reg_746_pp0_iter48_reg <= tmp_27_reg_746_pp0_iter47_reg;
        tmp_27_reg_746_pp0_iter49_reg <= tmp_27_reg_746_pp0_iter48_reg;
        tmp_27_reg_746_pp0_iter4_reg <= tmp_27_reg_746_pp0_iter3_reg;
        tmp_27_reg_746_pp0_iter50_reg <= tmp_27_reg_746_pp0_iter49_reg;
        tmp_27_reg_746_pp0_iter51_reg <= tmp_27_reg_746_pp0_iter50_reg;
        tmp_27_reg_746_pp0_iter52_reg <= tmp_27_reg_746_pp0_iter51_reg;
        tmp_27_reg_746_pp0_iter53_reg <= tmp_27_reg_746_pp0_iter52_reg;
        tmp_27_reg_746_pp0_iter54_reg <= tmp_27_reg_746_pp0_iter53_reg;
        tmp_27_reg_746_pp0_iter55_reg <= tmp_27_reg_746_pp0_iter54_reg;
        tmp_27_reg_746_pp0_iter56_reg <= tmp_27_reg_746_pp0_iter55_reg;
        tmp_27_reg_746_pp0_iter57_reg <= tmp_27_reg_746_pp0_iter56_reg;
        tmp_27_reg_746_pp0_iter58_reg <= tmp_27_reg_746_pp0_iter57_reg;
        tmp_27_reg_746_pp0_iter59_reg <= tmp_27_reg_746_pp0_iter58_reg;
        tmp_27_reg_746_pp0_iter5_reg <= tmp_27_reg_746_pp0_iter4_reg;
        tmp_27_reg_746_pp0_iter60_reg <= tmp_27_reg_746_pp0_iter59_reg;
        tmp_27_reg_746_pp0_iter61_reg <= tmp_27_reg_746_pp0_iter60_reg;
        tmp_27_reg_746_pp0_iter62_reg <= tmp_27_reg_746_pp0_iter61_reg;
        tmp_27_reg_746_pp0_iter63_reg <= tmp_27_reg_746_pp0_iter62_reg;
        tmp_27_reg_746_pp0_iter64_reg <= tmp_27_reg_746_pp0_iter63_reg;
        tmp_27_reg_746_pp0_iter6_reg <= tmp_27_reg_746_pp0_iter5_reg;
        tmp_27_reg_746_pp0_iter7_reg <= tmp_27_reg_746_pp0_iter6_reg;
        tmp_27_reg_746_pp0_iter8_reg <= tmp_27_reg_746_pp0_iter7_reg;
        tmp_27_reg_746_pp0_iter9_reg <= tmp_27_reg_746_pp0_iter8_reg;
        tmp_2_reg_738_pp0_iter10_reg <= tmp_2_reg_738_pp0_iter9_reg;
        tmp_2_reg_738_pp0_iter11_reg <= tmp_2_reg_738_pp0_iter10_reg;
        tmp_2_reg_738_pp0_iter12_reg <= tmp_2_reg_738_pp0_iter11_reg;
        tmp_2_reg_738_pp0_iter13_reg <= tmp_2_reg_738_pp0_iter12_reg;
        tmp_2_reg_738_pp0_iter14_reg <= tmp_2_reg_738_pp0_iter13_reg;
        tmp_2_reg_738_pp0_iter15_reg <= tmp_2_reg_738_pp0_iter14_reg;
        tmp_2_reg_738_pp0_iter16_reg <= tmp_2_reg_738_pp0_iter15_reg;
        tmp_2_reg_738_pp0_iter17_reg <= tmp_2_reg_738_pp0_iter16_reg;
        tmp_2_reg_738_pp0_iter18_reg <= tmp_2_reg_738_pp0_iter17_reg;
        tmp_2_reg_738_pp0_iter19_reg <= tmp_2_reg_738_pp0_iter18_reg;
        tmp_2_reg_738_pp0_iter1_reg <= tmp_2_reg_738;
        tmp_2_reg_738_pp0_iter20_reg <= tmp_2_reg_738_pp0_iter19_reg;
        tmp_2_reg_738_pp0_iter21_reg <= tmp_2_reg_738_pp0_iter20_reg;
        tmp_2_reg_738_pp0_iter22_reg <= tmp_2_reg_738_pp0_iter21_reg;
        tmp_2_reg_738_pp0_iter23_reg <= tmp_2_reg_738_pp0_iter22_reg;
        tmp_2_reg_738_pp0_iter24_reg <= tmp_2_reg_738_pp0_iter23_reg;
        tmp_2_reg_738_pp0_iter25_reg <= tmp_2_reg_738_pp0_iter24_reg;
        tmp_2_reg_738_pp0_iter26_reg <= tmp_2_reg_738_pp0_iter25_reg;
        tmp_2_reg_738_pp0_iter27_reg <= tmp_2_reg_738_pp0_iter26_reg;
        tmp_2_reg_738_pp0_iter28_reg <= tmp_2_reg_738_pp0_iter27_reg;
        tmp_2_reg_738_pp0_iter29_reg <= tmp_2_reg_738_pp0_iter28_reg;
        tmp_2_reg_738_pp0_iter2_reg <= tmp_2_reg_738_pp0_iter1_reg;
        tmp_2_reg_738_pp0_iter30_reg <= tmp_2_reg_738_pp0_iter29_reg;
        tmp_2_reg_738_pp0_iter31_reg <= tmp_2_reg_738_pp0_iter30_reg;
        tmp_2_reg_738_pp0_iter32_reg <= tmp_2_reg_738_pp0_iter31_reg;
        tmp_2_reg_738_pp0_iter33_reg <= tmp_2_reg_738_pp0_iter32_reg;
        tmp_2_reg_738_pp0_iter34_reg <= tmp_2_reg_738_pp0_iter33_reg;
        tmp_2_reg_738_pp0_iter35_reg <= tmp_2_reg_738_pp0_iter34_reg;
        tmp_2_reg_738_pp0_iter36_reg <= tmp_2_reg_738_pp0_iter35_reg;
        tmp_2_reg_738_pp0_iter37_reg <= tmp_2_reg_738_pp0_iter36_reg;
        tmp_2_reg_738_pp0_iter38_reg <= tmp_2_reg_738_pp0_iter37_reg;
        tmp_2_reg_738_pp0_iter39_reg <= tmp_2_reg_738_pp0_iter38_reg;
        tmp_2_reg_738_pp0_iter3_reg <= tmp_2_reg_738_pp0_iter2_reg;
        tmp_2_reg_738_pp0_iter40_reg <= tmp_2_reg_738_pp0_iter39_reg;
        tmp_2_reg_738_pp0_iter41_reg <= tmp_2_reg_738_pp0_iter40_reg;
        tmp_2_reg_738_pp0_iter42_reg <= tmp_2_reg_738_pp0_iter41_reg;
        tmp_2_reg_738_pp0_iter43_reg <= tmp_2_reg_738_pp0_iter42_reg;
        tmp_2_reg_738_pp0_iter44_reg <= tmp_2_reg_738_pp0_iter43_reg;
        tmp_2_reg_738_pp0_iter45_reg <= tmp_2_reg_738_pp0_iter44_reg;
        tmp_2_reg_738_pp0_iter46_reg <= tmp_2_reg_738_pp0_iter45_reg;
        tmp_2_reg_738_pp0_iter47_reg <= tmp_2_reg_738_pp0_iter46_reg;
        tmp_2_reg_738_pp0_iter48_reg <= tmp_2_reg_738_pp0_iter47_reg;
        tmp_2_reg_738_pp0_iter49_reg <= tmp_2_reg_738_pp0_iter48_reg;
        tmp_2_reg_738_pp0_iter4_reg <= tmp_2_reg_738_pp0_iter3_reg;
        tmp_2_reg_738_pp0_iter50_reg <= tmp_2_reg_738_pp0_iter49_reg;
        tmp_2_reg_738_pp0_iter51_reg <= tmp_2_reg_738_pp0_iter50_reg;
        tmp_2_reg_738_pp0_iter52_reg <= tmp_2_reg_738_pp0_iter51_reg;
        tmp_2_reg_738_pp0_iter53_reg <= tmp_2_reg_738_pp0_iter52_reg;
        tmp_2_reg_738_pp0_iter54_reg <= tmp_2_reg_738_pp0_iter53_reg;
        tmp_2_reg_738_pp0_iter55_reg <= tmp_2_reg_738_pp0_iter54_reg;
        tmp_2_reg_738_pp0_iter56_reg <= tmp_2_reg_738_pp0_iter55_reg;
        tmp_2_reg_738_pp0_iter57_reg <= tmp_2_reg_738_pp0_iter56_reg;
        tmp_2_reg_738_pp0_iter58_reg <= tmp_2_reg_738_pp0_iter57_reg;
        tmp_2_reg_738_pp0_iter59_reg <= tmp_2_reg_738_pp0_iter58_reg;
        tmp_2_reg_738_pp0_iter5_reg <= tmp_2_reg_738_pp0_iter4_reg;
        tmp_2_reg_738_pp0_iter60_reg <= tmp_2_reg_738_pp0_iter59_reg;
        tmp_2_reg_738_pp0_iter61_reg <= tmp_2_reg_738_pp0_iter60_reg;
        tmp_2_reg_738_pp0_iter62_reg <= tmp_2_reg_738_pp0_iter61_reg;
        tmp_2_reg_738_pp0_iter63_reg <= tmp_2_reg_738_pp0_iter62_reg;
        tmp_2_reg_738_pp0_iter64_reg <= tmp_2_reg_738_pp0_iter63_reg;
        tmp_2_reg_738_pp0_iter6_reg <= tmp_2_reg_738_pp0_iter5_reg;
        tmp_2_reg_738_pp0_iter7_reg <= tmp_2_reg_738_pp0_iter6_reg;
        tmp_2_reg_738_pp0_iter8_reg <= tmp_2_reg_738_pp0_iter7_reg;
        tmp_2_reg_738_pp0_iter9_reg <= tmp_2_reg_738_pp0_iter8_reg;
        tmp_3_reg_742_pp0_iter10_reg <= tmp_3_reg_742_pp0_iter9_reg;
        tmp_3_reg_742_pp0_iter11_reg <= tmp_3_reg_742_pp0_iter10_reg;
        tmp_3_reg_742_pp0_iter12_reg <= tmp_3_reg_742_pp0_iter11_reg;
        tmp_3_reg_742_pp0_iter13_reg <= tmp_3_reg_742_pp0_iter12_reg;
        tmp_3_reg_742_pp0_iter14_reg <= tmp_3_reg_742_pp0_iter13_reg;
        tmp_3_reg_742_pp0_iter15_reg <= tmp_3_reg_742_pp0_iter14_reg;
        tmp_3_reg_742_pp0_iter16_reg <= tmp_3_reg_742_pp0_iter15_reg;
        tmp_3_reg_742_pp0_iter17_reg <= tmp_3_reg_742_pp0_iter16_reg;
        tmp_3_reg_742_pp0_iter18_reg <= tmp_3_reg_742_pp0_iter17_reg;
        tmp_3_reg_742_pp0_iter19_reg <= tmp_3_reg_742_pp0_iter18_reg;
        tmp_3_reg_742_pp0_iter1_reg <= tmp_3_reg_742;
        tmp_3_reg_742_pp0_iter20_reg <= tmp_3_reg_742_pp0_iter19_reg;
        tmp_3_reg_742_pp0_iter21_reg <= tmp_3_reg_742_pp0_iter20_reg;
        tmp_3_reg_742_pp0_iter22_reg <= tmp_3_reg_742_pp0_iter21_reg;
        tmp_3_reg_742_pp0_iter23_reg <= tmp_3_reg_742_pp0_iter22_reg;
        tmp_3_reg_742_pp0_iter24_reg <= tmp_3_reg_742_pp0_iter23_reg;
        tmp_3_reg_742_pp0_iter25_reg <= tmp_3_reg_742_pp0_iter24_reg;
        tmp_3_reg_742_pp0_iter26_reg <= tmp_3_reg_742_pp0_iter25_reg;
        tmp_3_reg_742_pp0_iter27_reg <= tmp_3_reg_742_pp0_iter26_reg;
        tmp_3_reg_742_pp0_iter28_reg <= tmp_3_reg_742_pp0_iter27_reg;
        tmp_3_reg_742_pp0_iter29_reg <= tmp_3_reg_742_pp0_iter28_reg;
        tmp_3_reg_742_pp0_iter2_reg <= tmp_3_reg_742_pp0_iter1_reg;
        tmp_3_reg_742_pp0_iter30_reg <= tmp_3_reg_742_pp0_iter29_reg;
        tmp_3_reg_742_pp0_iter31_reg <= tmp_3_reg_742_pp0_iter30_reg;
        tmp_3_reg_742_pp0_iter32_reg <= tmp_3_reg_742_pp0_iter31_reg;
        tmp_3_reg_742_pp0_iter33_reg <= tmp_3_reg_742_pp0_iter32_reg;
        tmp_3_reg_742_pp0_iter34_reg <= tmp_3_reg_742_pp0_iter33_reg;
        tmp_3_reg_742_pp0_iter35_reg <= tmp_3_reg_742_pp0_iter34_reg;
        tmp_3_reg_742_pp0_iter36_reg <= tmp_3_reg_742_pp0_iter35_reg;
        tmp_3_reg_742_pp0_iter37_reg <= tmp_3_reg_742_pp0_iter36_reg;
        tmp_3_reg_742_pp0_iter38_reg <= tmp_3_reg_742_pp0_iter37_reg;
        tmp_3_reg_742_pp0_iter39_reg <= tmp_3_reg_742_pp0_iter38_reg;
        tmp_3_reg_742_pp0_iter3_reg <= tmp_3_reg_742_pp0_iter2_reg;
        tmp_3_reg_742_pp0_iter40_reg <= tmp_3_reg_742_pp0_iter39_reg;
        tmp_3_reg_742_pp0_iter41_reg <= tmp_3_reg_742_pp0_iter40_reg;
        tmp_3_reg_742_pp0_iter42_reg <= tmp_3_reg_742_pp0_iter41_reg;
        tmp_3_reg_742_pp0_iter43_reg <= tmp_3_reg_742_pp0_iter42_reg;
        tmp_3_reg_742_pp0_iter44_reg <= tmp_3_reg_742_pp0_iter43_reg;
        tmp_3_reg_742_pp0_iter45_reg <= tmp_3_reg_742_pp0_iter44_reg;
        tmp_3_reg_742_pp0_iter46_reg <= tmp_3_reg_742_pp0_iter45_reg;
        tmp_3_reg_742_pp0_iter47_reg <= tmp_3_reg_742_pp0_iter46_reg;
        tmp_3_reg_742_pp0_iter48_reg <= tmp_3_reg_742_pp0_iter47_reg;
        tmp_3_reg_742_pp0_iter49_reg <= tmp_3_reg_742_pp0_iter48_reg;
        tmp_3_reg_742_pp0_iter4_reg <= tmp_3_reg_742_pp0_iter3_reg;
        tmp_3_reg_742_pp0_iter50_reg <= tmp_3_reg_742_pp0_iter49_reg;
        tmp_3_reg_742_pp0_iter51_reg <= tmp_3_reg_742_pp0_iter50_reg;
        tmp_3_reg_742_pp0_iter52_reg <= tmp_3_reg_742_pp0_iter51_reg;
        tmp_3_reg_742_pp0_iter53_reg <= tmp_3_reg_742_pp0_iter52_reg;
        tmp_3_reg_742_pp0_iter54_reg <= tmp_3_reg_742_pp0_iter53_reg;
        tmp_3_reg_742_pp0_iter55_reg <= tmp_3_reg_742_pp0_iter54_reg;
        tmp_3_reg_742_pp0_iter56_reg <= tmp_3_reg_742_pp0_iter55_reg;
        tmp_3_reg_742_pp0_iter57_reg <= tmp_3_reg_742_pp0_iter56_reg;
        tmp_3_reg_742_pp0_iter58_reg <= tmp_3_reg_742_pp0_iter57_reg;
        tmp_3_reg_742_pp0_iter59_reg <= tmp_3_reg_742_pp0_iter58_reg;
        tmp_3_reg_742_pp0_iter5_reg <= tmp_3_reg_742_pp0_iter4_reg;
        tmp_3_reg_742_pp0_iter60_reg <= tmp_3_reg_742_pp0_iter59_reg;
        tmp_3_reg_742_pp0_iter61_reg <= tmp_3_reg_742_pp0_iter60_reg;
        tmp_3_reg_742_pp0_iter62_reg <= tmp_3_reg_742_pp0_iter61_reg;
        tmp_3_reg_742_pp0_iter63_reg <= tmp_3_reg_742_pp0_iter62_reg;
        tmp_3_reg_742_pp0_iter64_reg <= tmp_3_reg_742_pp0_iter63_reg;
        tmp_3_reg_742_pp0_iter6_reg <= tmp_3_reg_742_pp0_iter5_reg;
        tmp_3_reg_742_pp0_iter7_reg <= tmp_3_reg_742_pp0_iter6_reg;
        tmp_3_reg_742_pp0_iter8_reg <= tmp_3_reg_742_pp0_iter7_reg;
        tmp_3_reg_742_pp0_iter9_reg <= tmp_3_reg_742_pp0_iter8_reg;
        tmp_4_reg_771_pp0_iter10_reg <= tmp_4_reg_771_pp0_iter9_reg;
        tmp_4_reg_771_pp0_iter11_reg <= tmp_4_reg_771_pp0_iter10_reg;
        tmp_4_reg_771_pp0_iter12_reg <= tmp_4_reg_771_pp0_iter11_reg;
        tmp_4_reg_771_pp0_iter13_reg <= tmp_4_reg_771_pp0_iter12_reg;
        tmp_4_reg_771_pp0_iter14_reg <= tmp_4_reg_771_pp0_iter13_reg;
        tmp_4_reg_771_pp0_iter15_reg <= tmp_4_reg_771_pp0_iter14_reg;
        tmp_4_reg_771_pp0_iter16_reg <= tmp_4_reg_771_pp0_iter15_reg;
        tmp_4_reg_771_pp0_iter17_reg <= tmp_4_reg_771_pp0_iter16_reg;
        tmp_4_reg_771_pp0_iter18_reg <= tmp_4_reg_771_pp0_iter17_reg;
        tmp_4_reg_771_pp0_iter19_reg <= tmp_4_reg_771_pp0_iter18_reg;
        tmp_4_reg_771_pp0_iter1_reg <= tmp_4_reg_771;
        tmp_4_reg_771_pp0_iter20_reg <= tmp_4_reg_771_pp0_iter19_reg;
        tmp_4_reg_771_pp0_iter21_reg <= tmp_4_reg_771_pp0_iter20_reg;
        tmp_4_reg_771_pp0_iter22_reg <= tmp_4_reg_771_pp0_iter21_reg;
        tmp_4_reg_771_pp0_iter23_reg <= tmp_4_reg_771_pp0_iter22_reg;
        tmp_4_reg_771_pp0_iter24_reg <= tmp_4_reg_771_pp0_iter23_reg;
        tmp_4_reg_771_pp0_iter25_reg <= tmp_4_reg_771_pp0_iter24_reg;
        tmp_4_reg_771_pp0_iter26_reg <= tmp_4_reg_771_pp0_iter25_reg;
        tmp_4_reg_771_pp0_iter27_reg <= tmp_4_reg_771_pp0_iter26_reg;
        tmp_4_reg_771_pp0_iter28_reg <= tmp_4_reg_771_pp0_iter27_reg;
        tmp_4_reg_771_pp0_iter29_reg <= tmp_4_reg_771_pp0_iter28_reg;
        tmp_4_reg_771_pp0_iter2_reg <= tmp_4_reg_771_pp0_iter1_reg;
        tmp_4_reg_771_pp0_iter30_reg <= tmp_4_reg_771_pp0_iter29_reg;
        tmp_4_reg_771_pp0_iter31_reg <= tmp_4_reg_771_pp0_iter30_reg;
        tmp_4_reg_771_pp0_iter32_reg <= tmp_4_reg_771_pp0_iter31_reg;
        tmp_4_reg_771_pp0_iter33_reg <= tmp_4_reg_771_pp0_iter32_reg;
        tmp_4_reg_771_pp0_iter34_reg <= tmp_4_reg_771_pp0_iter33_reg;
        tmp_4_reg_771_pp0_iter35_reg <= tmp_4_reg_771_pp0_iter34_reg;
        tmp_4_reg_771_pp0_iter36_reg <= tmp_4_reg_771_pp0_iter35_reg;
        tmp_4_reg_771_pp0_iter37_reg <= tmp_4_reg_771_pp0_iter36_reg;
        tmp_4_reg_771_pp0_iter38_reg <= tmp_4_reg_771_pp0_iter37_reg;
        tmp_4_reg_771_pp0_iter39_reg <= tmp_4_reg_771_pp0_iter38_reg;
        tmp_4_reg_771_pp0_iter3_reg <= tmp_4_reg_771_pp0_iter2_reg;
        tmp_4_reg_771_pp0_iter40_reg <= tmp_4_reg_771_pp0_iter39_reg;
        tmp_4_reg_771_pp0_iter41_reg <= tmp_4_reg_771_pp0_iter40_reg;
        tmp_4_reg_771_pp0_iter42_reg <= tmp_4_reg_771_pp0_iter41_reg;
        tmp_4_reg_771_pp0_iter43_reg <= tmp_4_reg_771_pp0_iter42_reg;
        tmp_4_reg_771_pp0_iter44_reg <= tmp_4_reg_771_pp0_iter43_reg;
        tmp_4_reg_771_pp0_iter45_reg <= tmp_4_reg_771_pp0_iter44_reg;
        tmp_4_reg_771_pp0_iter46_reg <= tmp_4_reg_771_pp0_iter45_reg;
        tmp_4_reg_771_pp0_iter47_reg <= tmp_4_reg_771_pp0_iter46_reg;
        tmp_4_reg_771_pp0_iter48_reg <= tmp_4_reg_771_pp0_iter47_reg;
        tmp_4_reg_771_pp0_iter49_reg <= tmp_4_reg_771_pp0_iter48_reg;
        tmp_4_reg_771_pp0_iter4_reg <= tmp_4_reg_771_pp0_iter3_reg;
        tmp_4_reg_771_pp0_iter50_reg <= tmp_4_reg_771_pp0_iter49_reg;
        tmp_4_reg_771_pp0_iter51_reg <= tmp_4_reg_771_pp0_iter50_reg;
        tmp_4_reg_771_pp0_iter52_reg <= tmp_4_reg_771_pp0_iter51_reg;
        tmp_4_reg_771_pp0_iter53_reg <= tmp_4_reg_771_pp0_iter52_reg;
        tmp_4_reg_771_pp0_iter54_reg <= tmp_4_reg_771_pp0_iter53_reg;
        tmp_4_reg_771_pp0_iter55_reg <= tmp_4_reg_771_pp0_iter54_reg;
        tmp_4_reg_771_pp0_iter56_reg <= tmp_4_reg_771_pp0_iter55_reg;
        tmp_4_reg_771_pp0_iter57_reg <= tmp_4_reg_771_pp0_iter56_reg;
        tmp_4_reg_771_pp0_iter58_reg <= tmp_4_reg_771_pp0_iter57_reg;
        tmp_4_reg_771_pp0_iter59_reg <= tmp_4_reg_771_pp0_iter58_reg;
        tmp_4_reg_771_pp0_iter5_reg <= tmp_4_reg_771_pp0_iter4_reg;
        tmp_4_reg_771_pp0_iter60_reg <= tmp_4_reg_771_pp0_iter59_reg;
        tmp_4_reg_771_pp0_iter61_reg <= tmp_4_reg_771_pp0_iter60_reg;
        tmp_4_reg_771_pp0_iter62_reg <= tmp_4_reg_771_pp0_iter61_reg;
        tmp_4_reg_771_pp0_iter63_reg <= tmp_4_reg_771_pp0_iter62_reg;
        tmp_4_reg_771_pp0_iter6_reg <= tmp_4_reg_771_pp0_iter5_reg;
        tmp_4_reg_771_pp0_iter7_reg <= tmp_4_reg_771_pp0_iter6_reg;
        tmp_4_reg_771_pp0_iter8_reg <= tmp_4_reg_771_pp0_iter7_reg;
        tmp_4_reg_771_pp0_iter9_reg <= tmp_4_reg_771_pp0_iter8_reg;
        tmp_s_reg_730 <= tmp_s_fu_191_p2;
        tmp_s_reg_730_pp0_iter10_reg <= tmp_s_reg_730_pp0_iter9_reg;
        tmp_s_reg_730_pp0_iter11_reg <= tmp_s_reg_730_pp0_iter10_reg;
        tmp_s_reg_730_pp0_iter12_reg <= tmp_s_reg_730_pp0_iter11_reg;
        tmp_s_reg_730_pp0_iter13_reg <= tmp_s_reg_730_pp0_iter12_reg;
        tmp_s_reg_730_pp0_iter14_reg <= tmp_s_reg_730_pp0_iter13_reg;
        tmp_s_reg_730_pp0_iter15_reg <= tmp_s_reg_730_pp0_iter14_reg;
        tmp_s_reg_730_pp0_iter16_reg <= tmp_s_reg_730_pp0_iter15_reg;
        tmp_s_reg_730_pp0_iter17_reg <= tmp_s_reg_730_pp0_iter16_reg;
        tmp_s_reg_730_pp0_iter18_reg <= tmp_s_reg_730_pp0_iter17_reg;
        tmp_s_reg_730_pp0_iter19_reg <= tmp_s_reg_730_pp0_iter18_reg;
        tmp_s_reg_730_pp0_iter1_reg <= tmp_s_reg_730;
        tmp_s_reg_730_pp0_iter20_reg <= tmp_s_reg_730_pp0_iter19_reg;
        tmp_s_reg_730_pp0_iter21_reg <= tmp_s_reg_730_pp0_iter20_reg;
        tmp_s_reg_730_pp0_iter22_reg <= tmp_s_reg_730_pp0_iter21_reg;
        tmp_s_reg_730_pp0_iter23_reg <= tmp_s_reg_730_pp0_iter22_reg;
        tmp_s_reg_730_pp0_iter24_reg <= tmp_s_reg_730_pp0_iter23_reg;
        tmp_s_reg_730_pp0_iter25_reg <= tmp_s_reg_730_pp0_iter24_reg;
        tmp_s_reg_730_pp0_iter26_reg <= tmp_s_reg_730_pp0_iter25_reg;
        tmp_s_reg_730_pp0_iter27_reg <= tmp_s_reg_730_pp0_iter26_reg;
        tmp_s_reg_730_pp0_iter28_reg <= tmp_s_reg_730_pp0_iter27_reg;
        tmp_s_reg_730_pp0_iter29_reg <= tmp_s_reg_730_pp0_iter28_reg;
        tmp_s_reg_730_pp0_iter2_reg <= tmp_s_reg_730_pp0_iter1_reg;
        tmp_s_reg_730_pp0_iter30_reg <= tmp_s_reg_730_pp0_iter29_reg;
        tmp_s_reg_730_pp0_iter31_reg <= tmp_s_reg_730_pp0_iter30_reg;
        tmp_s_reg_730_pp0_iter32_reg <= tmp_s_reg_730_pp0_iter31_reg;
        tmp_s_reg_730_pp0_iter33_reg <= tmp_s_reg_730_pp0_iter32_reg;
        tmp_s_reg_730_pp0_iter34_reg <= tmp_s_reg_730_pp0_iter33_reg;
        tmp_s_reg_730_pp0_iter35_reg <= tmp_s_reg_730_pp0_iter34_reg;
        tmp_s_reg_730_pp0_iter36_reg <= tmp_s_reg_730_pp0_iter35_reg;
        tmp_s_reg_730_pp0_iter37_reg <= tmp_s_reg_730_pp0_iter36_reg;
        tmp_s_reg_730_pp0_iter38_reg <= tmp_s_reg_730_pp0_iter37_reg;
        tmp_s_reg_730_pp0_iter39_reg <= tmp_s_reg_730_pp0_iter38_reg;
        tmp_s_reg_730_pp0_iter3_reg <= tmp_s_reg_730_pp0_iter2_reg;
        tmp_s_reg_730_pp0_iter40_reg <= tmp_s_reg_730_pp0_iter39_reg;
        tmp_s_reg_730_pp0_iter41_reg <= tmp_s_reg_730_pp0_iter40_reg;
        tmp_s_reg_730_pp0_iter42_reg <= tmp_s_reg_730_pp0_iter41_reg;
        tmp_s_reg_730_pp0_iter43_reg <= tmp_s_reg_730_pp0_iter42_reg;
        tmp_s_reg_730_pp0_iter44_reg <= tmp_s_reg_730_pp0_iter43_reg;
        tmp_s_reg_730_pp0_iter45_reg <= tmp_s_reg_730_pp0_iter44_reg;
        tmp_s_reg_730_pp0_iter46_reg <= tmp_s_reg_730_pp0_iter45_reg;
        tmp_s_reg_730_pp0_iter47_reg <= tmp_s_reg_730_pp0_iter46_reg;
        tmp_s_reg_730_pp0_iter48_reg <= tmp_s_reg_730_pp0_iter47_reg;
        tmp_s_reg_730_pp0_iter49_reg <= tmp_s_reg_730_pp0_iter48_reg;
        tmp_s_reg_730_pp0_iter4_reg <= tmp_s_reg_730_pp0_iter3_reg;
        tmp_s_reg_730_pp0_iter50_reg <= tmp_s_reg_730_pp0_iter49_reg;
        tmp_s_reg_730_pp0_iter51_reg <= tmp_s_reg_730_pp0_iter50_reg;
        tmp_s_reg_730_pp0_iter52_reg <= tmp_s_reg_730_pp0_iter51_reg;
        tmp_s_reg_730_pp0_iter53_reg <= tmp_s_reg_730_pp0_iter52_reg;
        tmp_s_reg_730_pp0_iter54_reg <= tmp_s_reg_730_pp0_iter53_reg;
        tmp_s_reg_730_pp0_iter55_reg <= tmp_s_reg_730_pp0_iter54_reg;
        tmp_s_reg_730_pp0_iter56_reg <= tmp_s_reg_730_pp0_iter55_reg;
        tmp_s_reg_730_pp0_iter57_reg <= tmp_s_reg_730_pp0_iter56_reg;
        tmp_s_reg_730_pp0_iter58_reg <= tmp_s_reg_730_pp0_iter57_reg;
        tmp_s_reg_730_pp0_iter59_reg <= tmp_s_reg_730_pp0_iter58_reg;
        tmp_s_reg_730_pp0_iter5_reg <= tmp_s_reg_730_pp0_iter4_reg;
        tmp_s_reg_730_pp0_iter60_reg <= tmp_s_reg_730_pp0_iter59_reg;
        tmp_s_reg_730_pp0_iter61_reg <= tmp_s_reg_730_pp0_iter60_reg;
        tmp_s_reg_730_pp0_iter62_reg <= tmp_s_reg_730_pp0_iter61_reg;
        tmp_s_reg_730_pp0_iter63_reg <= tmp_s_reg_730_pp0_iter62_reg;
        tmp_s_reg_730_pp0_iter64_reg <= tmp_s_reg_730_pp0_iter63_reg;
        tmp_s_reg_730_pp0_iter6_reg <= tmp_s_reg_730_pp0_iter5_reg;
        tmp_s_reg_730_pp0_iter7_reg <= tmp_s_reg_730_pp0_iter6_reg;
        tmp_s_reg_730_pp0_iter8_reg <= tmp_s_reg_730_pp0_iter7_reg;
        tmp_s_reg_730_pp0_iter9_reg <= tmp_s_reg_730_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_27_fu_215_p3 == 1'd0) & (tmp_3_fu_209_p2 == 1'd0) & (tmp_2_fu_203_p2 == 1'd0) & (tmp_1_fu_197_p2 == 1'd0) & (tmp_s_fu_191_p2 == 1'd0))) begin
        exp_tmp_V_reg_761 <= {{ireg_V_fu_223_p1[62:52]}};
        isneg_reg_755 <= ireg_V_fu_223_p1[32'd63];
        tmp_29_reg_750 <= tmp_29_fu_227_p1;
        tmp_31_reg_766 <= tmp_31_fu_249_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_19_reg_819 == 1'd0) & (tmp_27_reg_746_pp0_iter56_reg == 1'd0) & (tmp_3_reg_742_pp0_iter56_reg == 1'd0) & (tmp_2_reg_738_pp0_iter56_reg == 1'd0) & (tmp_1_reg_734_pp0_iter56_reg == 1'd0) & (tmp_s_reg_730_pp0_iter56_reg == 1'd0))) begin
        is_neg_reg_828 <= z_V_reg_813[32'd54];
        msb_idx_reg_839 <= msb_idx_fu_543_p2;
        p_Val2_28_reg_833 <= p_Val2_28_fu_507_p3;
        tmp_34_reg_844 <= tmp_34_fu_549_p1;
        tmp_35_reg_849 <= msb_idx_fu_543_p2[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_27_reg_746 == 1'd0) & (tmp_3_reg_742 == 1'd0) & (tmp_2_reg_738 == 1'd0) & (tmp_1_reg_734 == 1'd0) & (tmp_s_reg_730 == 1'd0))) begin
        man_V_2_reg_776 <= man_V_2_fu_285_p3;
        sh_amt_reg_795 <= sh_amt_fu_315_p3;
        tmp_10_reg_802 <= tmp_10_fu_323_p2;
        tmp_7_reg_783 <= tmp_7_fu_292_p2;
        tmp_8_reg_789 <= tmp_8_fu_303_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_27_reg_746_pp0_iter1_reg == 1'd0) & (tmp_3_reg_742_pp0_iter1_reg == 1'd0) & (tmp_2_reg_738_pp0_iter1_reg == 1'd0) & (tmp_1_reg_734_pp0_iter1_reg == 1'd0) & (tmp_s_reg_730_pp0_iter1_reg == 1'd0))) begin
        t_V_reg_808 <= t_V_fu_480_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_19_reg_819_pp0_iter57_reg == 1'd0) & (tmp_27_reg_746_pp0_iter57_reg == 1'd0) & (tmp_3_reg_742_pp0_iter57_reg == 1'd0) & (tmp_2_reg_738_pp0_iter57_reg == 1'd0) & (tmp_1_reg_734_pp0_iter57_reg == 1'd0) & (tmp_s_reg_730_pp0_iter57_reg == 1'd0))) begin
        tmp32_V_3_reg_854 <= tmp32_V_3_fu_625_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_19_reg_819_pp0_iter63_reg == 1'd0) & (tmp_27_reg_746_pp0_iter63_reg == 1'd0) & (tmp_3_reg_742_pp0_iter63_reg == 1'd0) & (tmp_2_reg_738_pp0_iter63_reg == 1'd0) & (tmp_1_reg_734_pp0_iter63_reg == 1'd0) & (tmp_s_reg_730_pp0_iter63_reg == 1'd0))) begin
        tmp32_V_6_reg_859 <= tmp32_V_6_fu_633_p1;
        tmp_23_reg_864 <= tmp_23_fu_647_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_27_reg_746_pp0_iter55_reg == 1'd0) & (tmp_3_reg_742_pp0_iter55_reg == 1'd0) & (tmp_2_reg_738_pp0_iter55_reg == 1'd0) & (tmp_1_reg_734_pp0_iter55_reg == 1'd0) & (tmp_s_reg_730_pp0_iter55_reg == 1'd0))) begin
        tmp_19_reg_819 <= tmp_19_fu_488_p2;
        z_V_reg_813 <= grp_doublecordic_apfixed_fu_135_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_s_fu_191_p2 == 1'd0))) begin
        tmp_1_reg_734 <= tmp_1_fu_197_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_19_fu_488_p2 == 1'd0) & (tmp_27_reg_746_pp0_iter55_reg == 1'd0) & (tmp_3_reg_742_pp0_iter55_reg == 1'd0) & (tmp_2_reg_738_pp0_iter55_reg == 1'd0) & (tmp_1_reg_734_pp0_iter55_reg == 1'd0) & (tmp_s_reg_730_pp0_iter55_reg == 1'd0))) begin
        tmp_20_reg_823 <= tmp_20_fu_494_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_3_fu_209_p2 == 1'd0) & (tmp_2_fu_203_p2 == 1'd0) & (tmp_1_fu_197_p2 == 1'd0) & (tmp_s_fu_191_p2 == 1'd0))) begin
        tmp_27_reg_746 <= p_Val2_s_fu_146_p1[32'd30];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_fu_197_p2 == 1'd0) & (tmp_s_fu_191_p2 == 1'd0))) begin
        tmp_2_reg_738 <= tmp_2_fu_203_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_fu_203_p2 == 1'd0) & (tmp_1_fu_197_p2 == 1'd0) & (tmp_s_fu_191_p2 == 1'd0))) begin
        tmp_3_reg_742 <= tmp_3_fu_209_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_3_fu_209_p2 == 1'd1) & (tmp_2_fu_203_p2 == 1'd0) & (tmp_1_fu_197_p2 == 1'd0) & (tmp_s_fu_191_p2 == 1'd0))) begin
        tmp_4_reg_771 <= tmp_4_fu_253_p2;
    end
end

always @ (*) begin
    if (((tmp_19_reg_819_pp0_iter64_reg == 1'd0) & (tmp_27_reg_746_pp0_iter64_reg == 1'd0) & (tmp_3_reg_742_pp0_iter64_reg == 1'd0) & (tmp_2_reg_738_pp0_iter64_reg == 1'd0) & (tmp_1_reg_734_pp0_iter64_reg == 1'd0) & (tmp_s_reg_730_pp0_iter64_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_out_5_phi_fu_115_p14 = f_fu_694_p1;
    end else begin
        ap_phi_mux_out_5_phi_fu_115_p14 = ap_phi_reg_pp0_iter65_out_5_reg_110;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        grp_doublecordic_apfixed_fu_135_ap_ce = 1'b1;
    end else begin
        grp_doublecordic_apfixed_fu_135_ap_ce = 1'b0;
    end
end

assign F2_fu_297_p2 = (12'd1075 - tmp_6_fu_259_p1);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter31 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter32 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter33 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter34 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage0_iter35 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter36 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage0_iter37 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage0_iter38 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage0_iter39 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage0_iter40 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage0_iter41 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage0_iter42 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage0_iter43 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage0_iter44 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage0_iter45 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage0_iter46 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp0_stage0_iter47 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp0_stage0_iter48 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp0_stage0_iter49 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp0_stage0_iter50 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp0_stage0_iter51 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp0_stage0_iter52 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp0_stage0_iter53 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp0_stage0_iter54 = ~(1'b1 == 1'b1);

assign ap_block_state56_pp0_stage0_iter55 = ~(1'b1 == 1'b1);

assign ap_block_state57_pp0_stage0_iter56 = ~(1'b1 == 1'b1);

assign ap_block_state58_pp0_stage0_iter57 = ~(1'b1 == 1'b1);

assign ap_block_state59_pp0_stage0_iter58 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state60_pp0_stage0_iter59 = ~(1'b1 == 1'b1);

assign ap_block_state61_pp0_stage0_iter60 = ~(1'b1 == 1'b1);

assign ap_block_state62_pp0_stage0_iter61 = ~(1'b1 == 1'b1);

assign ap_block_state63_pp0_stage0_iter62 = ~(1'b1 == 1'b1);

assign ap_block_state64_pp0_stage0_iter63 = ~(1'b1 == 1'b1);

assign ap_block_state65_pp0_stage0_iter64 = ~(1'b1 == 1'b1);

assign ap_block_state66_pp0_stage0_iter65 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1514 = ((tmp_19_reg_819 == 1'd1) & (tmp_27_reg_746_pp0_iter56_reg == 1'd0) & (tmp_3_reg_742_pp0_iter56_reg == 1'd0) & (tmp_2_reg_738_pp0_iter56_reg == 1'd0) & (tmp_1_reg_734_pp0_iter56_reg == 1'd0) & (tmp_s_reg_730_pp0_iter56_reg == 1'd0));
end

always @ (*) begin
    ap_condition_773 = ((tmp_3_reg_742_pp0_iter63_reg == 1'd1) & (tmp_2_reg_738_pp0_iter63_reg == 1'd0) & (tmp_1_reg_734_pp0_iter63_reg == 1'd0) & (tmp_s_reg_730_pp0_iter63_reg == 1'd0));
end

assign ap_phi_reg_pp0_iter0_out_5_reg_110 = 'bx;

always @ (*) begin
    ap_predicate_op133_call_state4 = ((tmp_27_reg_746_pp0_iter2_reg == 1'd0) & (tmp_3_reg_742_pp0_iter2_reg == 1'd0) & (tmp_2_reg_738_pp0_iter2_reg == 1'd0) & (tmp_1_reg_734_pp0_iter2_reg == 1'd0) & (tmp_s_reg_730_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op186_call_state57 = ((tmp_27_reg_746_pp0_iter55_reg == 1'd0) & (tmp_3_reg_742_pp0_iter55_reg == 1'd0) & (tmp_2_reg_738_pp0_iter55_reg == 1'd0) & (tmp_1_reg_734_pp0_iter55_reg == 1'd0) & (tmp_s_reg_730_pp0_iter55_reg == 1'd0));
end

assign ap_return = ((p_Result_s_reg_720_pp0_iter64_reg[0:0] === 1'b1) ? out_fu_709_p1 : ap_phi_mux_out_5_phi_fu_115_p14);

assign d_assign_fu_143_p0 = ((p_Result_s_fu_150_p3[0:0] === 1'b1) ? inabs_fu_178_p1 : in_r_int_reg);

assign exp_V_fu_262_p2 = ($signed(12'd3073) + $signed(tmp_6_fu_259_p1));

assign f_fu_694_p1 = p_Result_35_fu_683_p5;

assign icmp_fu_581_p2 = ((tmp_36_fu_571_p4 == 26'd0) ? 1'b1 : 1'b0);

assign inabs_fu_178_p1 = inabs_neg_fu_172_p2;

assign inabs_neg_fu_172_p2 = (p_Val2_s_fu_146_p1 ^ 32'd2147483648);

assign ireg_V_fu_223_p1 = d_assign_fu_143_p1;

assign is_neg_fu_500_p3 = z_V_reg_813[32'd54];

assign loc_V_2_fu_168_p1 = p_Val2_s_fu_146_p1[22:0];

assign loc_V_fu_158_p4 = {{p_Val2_s_fu_146_p1[30:23]}};

assign man_V_1_fu_279_p2 = (54'd0 - p_Result_32_fu_275_p1);

assign man_V_2_fu_285_p3 = ((isneg_reg_755[0:0] === 1'b1) ? man_V_1_fu_279_p2 : p_Result_32_fu_275_p1);

assign msb_idx_1_fu_561_p3 = ((tmp_35_reg_849[0:0] === 1'b1) ? 31'd0 : tmp_34_reg_844);

assign msb_idx_3_cast_fu_567_p1 = msb_idx_1_fu_561_p3;

assign msb_idx_fu_543_p2 = (32'd54 - num_zeros_fu_539_p1);

assign newSel1_fu_449_p3 = ((sel_tmp_fu_406_p2[0:0] === 1'b1) ? tmp_222_cast_fu_358_p3 : man_V_2_reg_776);

assign newSel28_cast_fu_456_p1 = $signed(newSel1_fu_449_p3);

assign newSel2_fu_466_p3 = ((or_cond_fu_443_p2[0:0] === 1'b1) ? newSel_fu_435_p3 : newSel28_cast_fu_456_p1);

assign newSel_fu_435_p3 = ((sel_tmp5_fu_429_p2[0:0] === 1'b1) ? tmp_18_fu_369_p2 : tmp_16_fu_354_p1);

assign num_zeros_fu_539_p1 = tmp_21_fu_531_p3[31:0];

assign or_cond1_fu_460_p2 = (sel_tmp_fu_406_p2 | sel_tmp3_fu_380_p2);

assign or_cond2_fu_474_p2 = (or_cond_fu_443_p2 | or_cond1_fu_460_p2);

assign or_cond_fu_443_p2 = (sel_tmp5_fu_429_p2 | sel_tmp1_fu_412_p2);

assign out_1_fu_182_p3 = ((p_Result_s_fu_150_p3[0:0] === 1'b1) ? inabs_fu_178_p1 : in_r_int_reg);

assign out_fu_709_p1 = out_neg_fu_703_p2;

assign out_neg_fu_703_p2 = (out_to_int_fu_699_p1 ^ 32'd2147483648);

assign out_to_int_fu_699_p1 = ap_phi_mux_out_5_phi_fu_115_p14;

assign p_Repl2_46_trunc_fu_670_p2 = (tmp_43_fu_660_p1 + tmp27_cast_cast_fu_663_p3);

assign p_Result_32_fu_275_p1 = tmp_fu_268_p3;

integer ap_tvar_int_0;

always @ (p_Val2_28_fu_507_p3) begin
    for (ap_tvar_int_0 = 55 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 54 - 0) begin
            p_Result_33_fu_513_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_33_fu_513_p4[ap_tvar_int_0] = p_Val2_28_fu_507_p3[54 - ap_tvar_int_0];
        end
    end
end

assign p_Result_34_fu_523_p3 = {{9'd511}, {p_Result_33_fu_513_p4}};

assign p_Result_35_fu_683_p5 = {{tmp_24_fu_676_p3}, {tmp32_V_6_reg_859[22:0]}};

assign p_Result_5_fu_637_p4 = {{tmp32_V_6_fu_633_p1[30:23]}};

assign p_Result_s_fu_150_p3 = p_Val2_s_fu_146_p1[32'd31];

assign p_Val2_28_fu_507_p3 = ((is_neg_fu_500_p3[0:0] === 1'b1) ? tmp_20_reg_823 : z_V_reg_813);

assign p_Val2_s_fu_146_p1 = in_r_int_reg;

assign p_s_fu_653_p3 = ((tmp_4_reg_771_pp0_iter63_reg[0:0] === 1'b1) ? 32'd1070141403 : 32'd2147483647);

assign sel_tmp1_fu_412_p2 = (tmp_12_fu_335_p2 & sel_tmp8_fu_395_p2);

assign sel_tmp22_demorgan_fu_418_p2 = (tmp_8_reg_789 | sel_tmp7_demorgan_fu_385_p2);

assign sel_tmp2_fu_375_p2 = (tmp_7_reg_783 ^ 1'd1);

assign sel_tmp3_fu_380_p2 = (tmp_10_reg_802 & sel_tmp2_fu_375_p2);

assign sel_tmp4_fu_423_p2 = (sel_tmp22_demorgan_fu_418_p2 ^ 1'd1);

assign sel_tmp5_fu_429_p2 = (tmp_13_fu_340_p2 & sel_tmp4_fu_423_p2);

assign sel_tmp7_demorgan_fu_385_p2 = (tmp_7_reg_783 | tmp_10_reg_802);

assign sel_tmp7_fu_389_p2 = (sel_tmp7_demorgan_fu_385_p2 ^ 1'd1);

assign sel_tmp8_fu_395_p2 = (tmp_8_reg_789 & sel_tmp7_fu_389_p2);

assign sel_tmp9_fu_400_p2 = (tmp_12_fu_335_p2 ^ 1'd1);

assign sel_tmp_fu_406_p2 = (sel_tmp9_fu_400_p2 & sel_tmp8_fu_395_p2);

assign sh_amt_cast_fu_329_p1 = sh_amt_reg_795;

assign sh_amt_fu_315_p3 = ((tmp_8_fu_303_p2[0:0] === 1'b1) ? tmp_9_fu_309_p2 : exp_V_fu_262_p2);

assign t_V_fu_480_p3 = ((or_cond2_fu_474_p2[0:0] === 1'b1) ? newSel2_fu_466_p3 : 55'd0);

assign tmp27_cast_cast_fu_663_p3 = ((tmp_23_reg_864[0:0] === 1'b1) ? 8'd76 : 8'd75);

assign tmp32_V_1_fu_596_p2 = tmp32_V_fu_587_p1 << tmp_22_fu_590_p2;

assign tmp32_V_2_fu_621_p1 = tmp_41_fu_616_p2[31:0];

assign tmp32_V_3_fu_625_p3 = ((icmp_fu_581_p2[0:0] === 1'b1) ? tmp32_V_1_fu_596_p2 : tmp32_V_2_fu_621_p1);

assign tmp32_V_6_fu_633_p1 = grp_fu_140_p1;

assign tmp32_V_fu_587_p1 = p_Val2_28_reg_833[31:0];

assign tmp_10_fu_323_p2 = ((exp_V_fu_262_p2 == 12'd0) ? 1'b1 : 1'b0);

assign tmp_11_fu_332_p1 = man_V_2_reg_776;

assign tmp_12_fu_335_p2 = ((sh_amt_reg_795 < 12'd54) ? 1'b1 : 1'b0);

assign tmp_13_fu_340_p2 = ((sh_amt_reg_795 < 12'd55) ? 1'b1 : 1'b0);

assign tmp_14_fu_345_p1 = $unsigned(sh_amt_cast_fu_329_p1);

assign tmp_15_fu_349_p2 = $signed(man_V_2_reg_776) >>> tmp_14_fu_345_p1;

assign tmp_16_fu_354_p1 = $signed(tmp_15_fu_349_p2);

assign tmp_17_fu_365_p1 = $unsigned(sh_amt_cast_fu_329_p1);

assign tmp_18_fu_369_p2 = tmp_11_fu_332_p1 << tmp_17_fu_365_p1;

assign tmp_19_fu_488_p2 = ((grp_doublecordic_apfixed_fu_135_ap_return == 55'd0) ? 1'b1 : 1'b0);

assign tmp_1_fu_197_p2 = ((loc_V_fu_158_p4 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_20_fu_494_p2 = (55'd0 - grp_doublecordic_apfixed_fu_135_ap_return);


always @ (p_Result_34_fu_523_p3) begin
    if (p_Result_34_fu_523_p3[0] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd0;
    end else if (p_Result_34_fu_523_p3[1] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd1;
    end else if (p_Result_34_fu_523_p3[2] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd2;
    end else if (p_Result_34_fu_523_p3[3] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd3;
    end else if (p_Result_34_fu_523_p3[4] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd4;
    end else if (p_Result_34_fu_523_p3[5] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd5;
    end else if (p_Result_34_fu_523_p3[6] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd6;
    end else if (p_Result_34_fu_523_p3[7] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd7;
    end else if (p_Result_34_fu_523_p3[8] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd8;
    end else if (p_Result_34_fu_523_p3[9] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd9;
    end else if (p_Result_34_fu_523_p3[10] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd10;
    end else if (p_Result_34_fu_523_p3[11] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd11;
    end else if (p_Result_34_fu_523_p3[12] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd12;
    end else if (p_Result_34_fu_523_p3[13] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd13;
    end else if (p_Result_34_fu_523_p3[14] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd14;
    end else if (p_Result_34_fu_523_p3[15] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd15;
    end else if (p_Result_34_fu_523_p3[16] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd16;
    end else if (p_Result_34_fu_523_p3[17] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd17;
    end else if (p_Result_34_fu_523_p3[18] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd18;
    end else if (p_Result_34_fu_523_p3[19] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd19;
    end else if (p_Result_34_fu_523_p3[20] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd20;
    end else if (p_Result_34_fu_523_p3[21] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd21;
    end else if (p_Result_34_fu_523_p3[22] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd22;
    end else if (p_Result_34_fu_523_p3[23] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd23;
    end else if (p_Result_34_fu_523_p3[24] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd24;
    end else if (p_Result_34_fu_523_p3[25] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd25;
    end else if (p_Result_34_fu_523_p3[26] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd26;
    end else if (p_Result_34_fu_523_p3[27] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd27;
    end else if (p_Result_34_fu_523_p3[28] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd28;
    end else if (p_Result_34_fu_523_p3[29] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd29;
    end else if (p_Result_34_fu_523_p3[30] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd30;
    end else if (p_Result_34_fu_523_p3[31] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd31;
    end else if (p_Result_34_fu_523_p3[32] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd32;
    end else if (p_Result_34_fu_523_p3[33] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd33;
    end else if (p_Result_34_fu_523_p3[34] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd34;
    end else if (p_Result_34_fu_523_p3[35] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd35;
    end else if (p_Result_34_fu_523_p3[36] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd36;
    end else if (p_Result_34_fu_523_p3[37] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd37;
    end else if (p_Result_34_fu_523_p3[38] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd38;
    end else if (p_Result_34_fu_523_p3[39] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd39;
    end else if (p_Result_34_fu_523_p3[40] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd40;
    end else if (p_Result_34_fu_523_p3[41] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd41;
    end else if (p_Result_34_fu_523_p3[42] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd42;
    end else if (p_Result_34_fu_523_p3[43] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd43;
    end else if (p_Result_34_fu_523_p3[44] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd44;
    end else if (p_Result_34_fu_523_p3[45] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd45;
    end else if (p_Result_34_fu_523_p3[46] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd46;
    end else if (p_Result_34_fu_523_p3[47] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd47;
    end else if (p_Result_34_fu_523_p3[48] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd48;
    end else if (p_Result_34_fu_523_p3[49] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd49;
    end else if (p_Result_34_fu_523_p3[50] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd50;
    end else if (p_Result_34_fu_523_p3[51] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd51;
    end else if (p_Result_34_fu_523_p3[52] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd52;
    end else if (p_Result_34_fu_523_p3[53] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd53;
    end else if (p_Result_34_fu_523_p3[54] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd54;
    end else if (p_Result_34_fu_523_p3[55] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd55;
    end else if (p_Result_34_fu_523_p3[56] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd56;
    end else if (p_Result_34_fu_523_p3[57] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd57;
    end else if (p_Result_34_fu_523_p3[58] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd58;
    end else if (p_Result_34_fu_523_p3[59] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd59;
    end else if (p_Result_34_fu_523_p3[60] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd60;
    end else if (p_Result_34_fu_523_p3[61] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd61;
    end else if (p_Result_34_fu_523_p3[62] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd62;
    end else if (p_Result_34_fu_523_p3[63] == 1'b1) begin
        tmp_21_fu_531_p3 = 64'd63;
    end else begin
        tmp_21_fu_531_p3 = 64'd64;
    end
end

assign tmp_222_cast_fu_358_p3 = ((isneg_reg_755_pp0_iter1_reg[0:0] === 1'b1) ? 54'd18014398509481983 : 54'd0);

assign tmp_22_fu_590_p2 = (32'd31 - msb_idx_3_cast_fu_567_p1);

assign tmp_23_fu_647_p2 = ((p_Result_5_fu_637_p4 != 8'd158) ? 1'b1 : 1'b0);

assign tmp_24_fu_676_p3 = {{is_neg_reg_828_pp0_iter64_reg}, {p_Repl2_46_trunc_fu_670_p2}};

assign tmp_27_fu_215_p3 = p_Val2_s_fu_146_p1[32'd30];

assign tmp_29_fu_227_p1 = ireg_V_fu_223_p1[62:0];

assign tmp_2_fu_203_p2 = ((loc_V_fu_158_p4 < 8'd101) ? 1'b1 : 1'b0);

assign tmp_31_fu_249_p1 = ireg_V_fu_223_p1[51:0];

assign tmp_34_fu_549_p1 = msb_idx_fu_543_p2[30:0];

assign tmp_36_fu_571_p4 = {{msb_idx_1_fu_561_p3[30:5]}};

assign tmp_38_fu_602_p1 = msb_idx_1_fu_561_p3[5:0];

assign tmp_39_fu_606_p2 = ($signed(6'd33) + $signed(tmp_38_fu_602_p1));

assign tmp_3_fu_209_p2 = ((loc_V_fu_158_p4 == 8'd127) ? 1'b1 : 1'b0);

assign tmp_40_fu_612_p1 = tmp_39_fu_606_p2;

assign tmp_41_fu_616_p2 = p_Val2_28_reg_833 >> tmp_40_fu_612_p1;

assign tmp_43_fu_660_p1 = msb_idx_reg_839_pp0_iter64_reg[7:0];

assign tmp_4_fu_253_p2 = ((loc_V_2_fu_168_p1 == 23'd0) ? 1'b1 : 1'b0);

assign tmp_6_fu_259_p1 = exp_tmp_V_reg_761;

assign tmp_7_fu_292_p2 = ((tmp_29_reg_750 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_8_fu_303_p2 = (($signed(F2_fu_297_p2) > $signed(12'd52)) ? 1'b1 : 1'b0);

assign tmp_9_fu_309_p2 = ($signed(12'd4044) + $signed(F2_fu_297_p2));

assign tmp_fu_268_p3 = {{1'd1}, {tmp_31_reg_766}};

assign tmp_s_fu_191_p2 = ((loc_V_fu_158_p4 == 8'd255) ? 1'b1 : 1'b0);

endmodule //generic_asin_float_s
